### ISSUE TITLE
Failed OSBS build should fail execution

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#113]
Currently the return code is `0`, we should throw an exception.

**Comment by dbecvarik** [comment]
we are using check_call here - it should raise an exception. can you provide more detail?
Does rhpkg dies with proper exit code?

**Comment by goldmann** [comment]
It looks like rhpkg does not set the correct return code on failure... It needs to be reported upstream.

**Comment by dbecvarik** [comment]
As a workaround I'll implement parsing output for "FAILED" and we will see

**Comment by goldmann** [comment]
Relate to #183.

**Comment by goldmann** [comment]
I've tested it today and indeed, the issue is still not fixed. A build executed via `rhpkg` does not return a non-zero exit code when the build fails.

```
$ rhpkg container-build --target openjdk-11-rhel7-containers-candidate --scratch
Created task: 20188269
Task info: https://REDACTED/brew/taskinfo?taskID=20188269
Watching tasks (this may be safely interrupted)...
20188269 buildContainer (noarch): free
20188269 buildContainer (noarch): free -> open (x86-vm-17.build.eng.bos.redhat.com)
20188269 buildContainer (noarch): open (x86-vm-17.build.eng.bos.redhat.com) -> FAILED: Fault: <Fault 2001: "Image build failed. Error in plugin pull_base_image: RuntimeError(u'Unable to fetch manifest list for base image',). OSBS build id: scratch-47636-20190213112448">
  0 free  0 open  0 done  1 failed

20188269 buildContainer (noarch) failed
➜  openjdk git:(private-mgoldman-cekit) echo $?
0
```

**Comment by goldmann** [comment]
I've opened a ticket upstream: https://pagure.io/rpkg/issue/415.

**Comment by goldmann** [comment]
There are three things what we can do to solve this issue:

1. Wait for a fix upstream
2. Implement parsing of the output and fail the build if we think it failed.
3. Switch away from `rhpkg` and interact with the build system using `brew` calls directly, see https://github.com/cekit/cekit/issues/183.

I hope that upstream will agree with me that this is an issue and the fix for this will be fairly easy to implement resulting in rapid `rhpkg` tool update. Unfortunately this is totally out of my control and I don't know how long it could take.

Second option is something I don't want to implement. This is error prone and not the way it should be.

Third option is something that could be implemented especially since it also give us more flexibility in how we trigger builds.

**Comment by goldmann** [comment]
Example implementation of option 3 can be found here: https://github.com/cekit/cekit/pull/397. Tests were not adapted.
