### ISSUE TITLE
relative paths should be relative to the file specifying them

### ISSUE THREAD

**Issue by rcernich** [cekit/cekit#149]
For example, relative paths for artifacts defined in overrides.yaml should be relative to the overrides.yaml file, not the image.yaml.  This makes it difficult to use a single overrides file for multiple image builds, since the relative paths may be different.  I haven't verified whether or not relative paths work correctly with modules (i.e. if a module defines a resource itself).

**Comment by dbecvarik** [comment]
+1 on this,
I just need to update the code to know from where artifacts was defined. 
But this is mostly related to artifacts defined via 'path'?

**Comment by rcernich** [comment]
bump.  ran into this again the other day.  makes it difficult to use a standard overrides file for local development.  workaround is to use absolute paths, but that may be limiting in certain situations.

**Comment by dbecvarik** [comment]
I can do this, only issue is that this is probably breaking change. Also i would prefer all paths to be relative to one place, so maybe image.yaml location, wdyt @rcernich ?

**Comment by rcernich** [comment]
I don't think this is very helpful, as one use case is to override the locations of artifacts.  For example, if I make a change to openshift-ping, I put all the jars in one folder along with an overrides.yaml file.  I then use that same overrides file when building all the eap based images.

**Comment by dbecvarik** [comment]
oh that's a good point. I'll make the path relative to the descriptor which defines the artifact.
 Thanks, Will finish current work and this will be next thing I'll implement so it'll be part of the next minor release (1.5)

**Comment by rcernich** [comment]
that would be good, but also interesting, because what if an artifact is specified by a module? would that mean it would need to be located relative to the module itself?  we could get crazy and use some sort of search path, but that seems too complicated.  i wonder, thinking out loud, if resources are missing, if we could auto generate an overrides.yaml file that is stubbed out with the correct names.  users could then add path/url/git references to locate the missing resources.

**Comment by dbecvarik** [comment]
Other approach I was thinking about is to make paths relative only to overrides.yaml or image.yaml directories.
 This means that everything is relative to image.yaml directory, until its overridden. This feels best for me.

**Comment by rcernich** [comment]
that works for me.  i do like the idea about being able to stub out an overrides.yaml for missing resources.  The help text is nice, but the yaml gives you what you need to fix it.

**Comment by dbecvarik** [comment]
@goldmann @jmtd any opinions here? I want to ship this as part of 2.0 release.

**Comment by goldmann** [comment]
@dbecvarik I'm happy with whatever decision you think is best.

**Comment by dbecvarik** [comment]
@goldmann my only concern now is if all paths should be relative to image.yaml or all paths are relative to image.yaml except ones for overrides.yaml (which are relative to overrides.yaml)

I internally starting to prefer everything relative to image.yaml, which is easy to code and easy to explain and consistent

**Comment by rcernich** [comment]
I think if it's relative, it's relative to where it's defined.  At least, that seems natural to me.  At this point though, the only place we're specifying relative paths is in image.yaml and overrides.yaml, so...  I don't know if we'd ever have something like a module that configures repositories.  It doesn't seem like a valid use case (and could be prevented by disallowing `repositories` section in module.yaml files).

**Comment by dbecvarik** [comment]
being relative to even a module is probably valid approach too. 
And use case can be a config file/script which is injected to image. so instead of placing them to added, you can reference them as an artifacts and enable these files to be easily tweaked/overridden -> maybe it can be interesting for s2i modules?
