### ISSUE TITLE
always replace artifacts if no hash is specified

### ISSUE THREAD

**Issue by rcernich** [cekit/cekit#150]
In order to update artifacts from an upstream build (e.g. openshift-ping), the user is forced to delete the target directory (or at least the downloaded artifacts) for newer artifacts to be picked up by the image build.

**Comment by dbecvarik** [comment]
this is very good point, will look at ti today

**Comment by goldmann** [comment]
This must be documented.

**Comment by dbecvarik** [comment]
fixed in #211
