### ISSUE TITLE
Create new options for dist-git sync: --build-osbs-cp and --build-osbs-dev

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#166]
The `--build-osbs-cp` and `--build-osbs-dev` would change the target branch for dist git. This would be required to do syncs with dist-git branches other than the release branch without any code change. 

Example: EAP 7.1 repo, branch is `jb-eap-7.1-rhel-7`. From the release branch we can build it without specifying any custom branches, everything is fine. Assume now that we're doing anew dev build, from dev branch. This would require sync with the `jb-eap-7.1-dev-rhel-7` branch, not with `jb-eap-7.1-rhel-7`.

Specifying a custom branch name is out of scope for this ticket. Such ticket will be opened too. But here we're only interested into adding some shorthand switches which are much easier to remember than specifying whole branch name.

**Comment by dbecvarik** [comment]
So this is about switching branch in dist-git but using current local branch in image repo? Will image name also change somehow?

**Comment by goldmann** [comment]
That's correct. Image name stays the same.

**Comment by rcernich** [comment]
I mentioned this on #206, but I think a better solution for OSBS is to have a separate tool that wraps/invokes cekit.  This would allow all OSBS details to be managed separately from cekit.  It would also decouple support between cekit and OSBS (i.e. the OSBS features can evolve independently).

**Comment by goldmann** [comment]
@dbecvarik I would like to close it in favour of using overrides.
