### ISSUE TITLE
incorporate docker squash to docker build engine

### ISSUE THREAD

**Issue by dbecvarik** [cekit/cekit#188]
we should enable https://github.com/goldmann/docker-squash after docker build is done. 

it should be added as a separate option

**Comment by jmtd** [comment]
And/or look at docker build --squash support (from API 1.25 as experimental feature)

**Comment by dbecvarik** [comment]
i don't know if docker version in fedora/RHEL supports --squash o its hard here.

**Comment by goldmann** [comment]
Docker 1.13+ supports "native" squashing, but we don't control the daemon so we would need to ensure daemon is configured properly. Another thing - we did not test it at al.

**Comment by rcernich** [comment]
Perhaps it would be easier to add a docker section to the config where users could configure the docker flags they want to use for build, run, etc.

**Comment by rcernich** [comment]
Can we make this a priority?  After removing the intermediate images, the built -openshift images are very large.  I would also suggest making --build-squash=true the default.

**Comment by luck3y** [comment]
+1 for this please :)

**Comment by goldmann** [comment]
It looks like you guys like my tiny project :)

**Comment by goldmann** [comment]
This was incorporated with #329.
