### ISSUE TITLE
Cekit lacks the information about module versioning

### ISSUE THREAD

**Issue by dbecvarik** [cekit/cekit#196]
Cekit has very basic support for versioning modules and requesting precise module version. We should work on this story end finish to address issues like #194 

Very brief info is here https://concreate.readthedocs.io/en/latest/descriptor.html#module-installation . but it needs to be expanded/reworked/tested and properly documented

**Comment by jmtd** [comment]
That URI no longer works and s/concreate/cekit/ doesn't exist either

**Comment by goldmann** [comment]
Updated link: https://cekit.readthedocs.io/en/latest/descriptor/image.html#module-installation
