### ISSUE TITLE
Add warning/error when repository name is not explicitly specified

### ISSUE THREAD

**Issue by rcernich** [cekit/cekit#198]
The absence of a repository name makes it difficult to use overrides for building from local source.  I think there is another issue to document the auto-naming, which is mostly a problem for git repos, since the name includes the branch and .git suffix.  I'm guessing this is so you could use multiple versions of a repo in the same build, but is this something that would actually be done and if so, why?

**Comment by dbecvarik** [comment]
I would suggest linting sources, that every object which lacks explicit name will trigger warning not only git repository, wdyt?

**Comment by rcernich** [comment]
You'd need to consider artifacts.  I don't think it's common for them to use an explicit name.

**Comment by dbecvarik** [comment]
its not common but it creating weird issues with them with overriding them for community builds.

**Comment by rcernich** [comment]
Right.  i think there's another issue here with naming of the resources.  e.g. does it make sense to rename jars, etc. that we're pulling in?  I don't have any good answers here.

**Comment by dbecvarik** [comment]
We should probable rename them or introduce a way how to find them in scripts. But this needs to be analyzed more deeply probably. 
I'll postpone this probably for 2.1 release as 2.0 will already bring a lot of changes.

**Comment by rcernich** [comment]
yeah, it's really tricky.  it's almost like we'd want the name to be a proxy for the real artifact.  i know qe has commented in the past when building test images that have the version of the old resource instead of the new.

**Comment by goldmann** [comment]
I think this could be implemented generally, when a resource does not have a `name` explicitly specified, we could warn user that we use generated name.
