### ISSUE TITLE
Labels and env variables should be ordered alphabetically

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#207]
When generating the `Dockerfile`, every list should be ordered alphabetically so that subsequent generations generate the same content. Found this an issue with labels, not sure if affects other lists.

**Comment by dbecvarik** [comment]
We should be very careful here as this can be good for dockerfiles and env/labels. But this can be very problematic with scripts. 
This also can lead to related label rendered far from each other.

**Comment by goldmann** [comment]
Currently it's random which doesn't help either :)

**Comment by dbecvarik** [comment]
it list of maps. that should be deterministic somehow or maybe we have some worse hidden bug

**Comment by dbecvarik** [comment]
fixed by #209
