### ISSUE TITLE
Make it possible to customize the dist-git commit message

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#224]
Sometimes, when you execute overrides, it would be valuable to be able to specify the commit message.

**Comment by dbecvarik** [comment]
do you want commit to be adjustable via overrides.yaml or via command line? Or both?

**Comment by goldmann** [comment]
Only command line, I don't think it should be part of the descriptor at all.

**Comment by dbecvarik** [comment]
fixed by #299
