### ISSUE TITLE
Allow for JSON output

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#230]
Introduce new CLI flag, for example `--json` which will move logging to stderr and on stdout will return useful information about the process in JSON format.

**Comment by dbecvarik** [comment]
We need to define, what useful information are. we should probably output:
1) effective image descriptor
2) results of build
a) which build engine was used
b) details about image (tags, etc)
3) result of tests

**Comment by goldmann** [comment]
@rnc Do you think it's worth to add support for this? I don't see a use case for this currently, should we close it?

**Comment by goldmann** [comment]
There is no demand for it right now, rejecting.
