### ISSUE TITLE
Rewrite test documentation

### ISSUE THREAD

**Issue by dbecvarik** [cekit/cekit#232]
Test docs lacks good examples like:
* [x] how to test custom named image with Cekit 
* [x]  how to develop and run WIP tests
* [x] how tags are created and discovered
* [x] library of usable steps

**Comment by goldmann** [comment]
The attached PR rewrites the image testing documentation, there are still a few missing parts:

- We need to explain how tests are collected from repositories (image + modules)
- We need to cover how to write tests and features

To cover this, a separate issue was created: https://github.com/cekit/cekit/issues/422
