### ISSUE TITLE
Enhance test for tech-preview images

### ISSUE THREAD

**Issue by dbecvarik** [cekit/cekit#257]
We should look at tech-preview images and how we can enhance test maintenance for them.
@goldmann do you have any opinions here? Can we somehow help?

reference:
https://github.com/jboss-openshift/cct_module/pull/263

**Comment by goldmann** [comment]
I'll reference my comment in the other issue instead of copy/pasting it: https://github.com/jboss-openshift/cct_module/pull/263#issuecomment-400208056.

**Comment by dbecvarik** [comment]
Can you document your approach in our docs? it would be very helpful :)

**Comment by goldmann** [comment]
Rejecting. Tests and images should not use `-tech-preview` suffix. Instead it should be added only to released image.

Replacing with #559.
