### ISSUE TITLE
Prepare getting started guide with basic example

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#266]

**Comment by rnc** [comment]
@goldmann How about an example building an image using the https://github.com/jboss-container-images/openjdk/tree/openjdk18 repository perhaps with the centos image ?

**Comment by goldmann** [comment]
I was thinking about it but we need full control over it. Additionally we probably don't need an image with such many modules for a basic example.

Long time ago I created this:

* https://github.com/concrt/example-image-apollo
* https://github.com/concrt/example-image-tomcat
* https://github.com/concrt/example-common-module

Not sure if this works, but it was working. Maybe it would be good candidate?

**Comment by rnc** [comment]
Agreed, sounds good to me. How about we move example-common and example-image-tomcat to cekit and then add them as an example in the contributing.rst as part of #369 ?

**Comment by goldmann** [comment]
@rnc Is it safe to assume that you are working on this?

**Comment by rnc** [comment]
@goldmann Yes, I'll take this (after work in #398 is done )
