### ISSUE TITLE
Improve dependencies processing to only include modules once

### ISSUE THREAD

**Issue by rcernich** [cekit/cekit#27]
It appears that if a module includes another module, that module gets processed twice.  This may be OK, since it's unlikely there will be multiple versions of the same module, but we should probably keep track of which modules we've already processed so we can skip them in the future (i.e. first defined wins).  This may also highlight issues with dependencies if we run into a situation where the same dependency is defined more than once (which is only really a problem if the repositories are different, e.g. different git refs).

**Comment by rcernich** [comment]
In addition, I think we need to make sure dependencies are processed in order.  I'm not sure if this ties in with "required" modules or not, but I think we need to consider ensuring that for a module including/installing/requiring another module that the included/installed/required module is processed first.

**Comment by dbecvarik** [comment]
We should also probably try to detect circles in dependency graph to not process it Infinite loop.

**Comment by goldmann** [comment]
I don't think this is still relevant after 3.0 was released with the different approach to processing/installing modules. I'm going to close this one.
