### ISSUE TITLE
Move package repositories out of image/module.yaml

### ISSUE THREAD

**Issue by rcernich** [cekit/cekit#270]
The more I think about this, the more I think we shouldn't be defining package repositories within image/module.yaml files at all.  Given that these are specific to the build environment, even the specific build machine (whether or not it has active subscriptions), and that repositories may be structured differently from environment to environment (e.g. a single repository providing packages), it seems like it's more problematic to support these even with id's and overrides.

Having said that, I think we need some capability to list what packages are going to be installed so users can configure their repositories appropriately (probably also good to spit out a list of artifacts too).

**Comment by dbecvarik** [comment]
I think that we provide repository ids of suggested repositories. Me and @goldmann created some [suggestions](https://cekit.readthedocs.io/en/develop/repository_management.html). If you define repository with ``id`` only (plain repositories). Then they're only hints which repositories you need for fully subscribed system which is our primary target. Even our customer if they have custom mirrors will honor this structure so we need to make this as easy for them as possible.
Sure if they drop Red Hat way and do some customizations and merge repositories definition etc then they know what to do and can also define proper repository overrides or even will have repositories defined in custom base images. 
Please remember there is no easy way how to tell which repository you need to for particular packages so its almost impossible to get list of 10 packages and find repositories form which they come until you have access to repomd.xml

**Comment by rcernich** [comment]
> Please remember there is no easy way how to tell which repository you need to for particular packages so its almost impossible to get list of 10 packages and find repositories form which they come until you have access to repomd.xml

Right, but this is no different than running yum locally and trying to find where a package lives.  I agree that we should attempt to make things easier here, but it seems like there really isn't anything easy when it comes to packages.  Also, it seems google is pretty helpful in this regard, e.g. rh-maven35, https://centos.pkgs.org/7/centos-sclo-rh/rh-maven35-maven-3.5.0-4.2.el7.noarch.rpm.html.

The id's are helpful, but I'm still wondering if it's worth including them (e.g. as in a best-practice).  I'm leaning toward leaving them out.

That said, there is the issue with installing repositories from packages (e.g. centos scl, epel, etc.), which seems like a better fit for overrides.  Although, we could look at having platform specific settings in the config, where users could place these types of things.  (Maybe another enhancement is having a config command on the tool that allows users to modify their config without having to hand edit, e.g. cekit config add-repo --name scl --package centos-release-scl-rh --os centos, which would be paired with cekit build --os centos.)

I know we keep going round and around with regard to separating image metadata from build environment.  I'm hung up on the fact that the build environment affects how the image is created (e.g. how we resolve rh-maven35), not what goes into the image (rh-maven35).

**Comment by rcernich** [comment]
Using maven as an analogy, artifacts (dependencies) are defined within the project pom.xml (what), but the repository definitions are in the user's global settings.xml (from where).

**Comment by goldmann** [comment]
@rnc This is another one that we need to think about or close it.
