### ISSUE TITLE
description of configuration-vs-information env vars is slightly wrong

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#273]
I'm not sure if this is a bug in the description of environment variables here, or the definition of this environment variable in os-java-jolokia https://github.com/jboss-openshift/cct_module/blob/3eb41a31de9e799e2487675a285e386bb97d19b3/os-java-jolokia/module.yaml#L17:

> - name: AB_JOLOKIA_AUTH_OPENSHIFT
>  description: Switch on client authentication for OpenShift TLS communication. The value of this parameter can be a relative distinguished name which must be contained in a presented client's certificate. Enabling this parameter will automatically switch Jolokia into https communication mode. The default CA cert is set to `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`.
> value: "true"

https://github.com/cekit/cekit/blob/develop/docs/descriptor/envs.rst states

> Information environment variables… In most cases such environment variables *should not* be modified.
> Configuration environment variables …are **not** set during image build time but *can* be set at run time.

The description of AB_JOLOKIA_AUTH_OPENSHIFT strongly suggests it's a configuration variable, but it's set in the image.yaml so by the above definition it would be an Information environment variable.

**Comment by rcernich** [comment]
I think this is a documentation error, as we've moved away from configuration and information.  The sole distinguishing feature is whether or not it has a `value` field.  If it has a value, then the variable is added to the image.

**Comment by rnc** [comment]
I've reviewed the code, and while there are no _current_ tests for environment variables without a value (which there probably should be) it does indeed seem that if there is no `value` field it won't get generated into the image. I'll look at clarifying the docs.

**Comment by rnc** [comment]
Closing with #676
