### ISSUE TITLE
Drop python 2.x support

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#278]
Whilst implementing #272 I had to make two specific changes to fix problems with Python 2.7. Scaling up I suspect it has a non-trivial impact on developing the whole program.

Could we just drop python 2 support altogether? WDYT?

**Comment by rcernich** [comment]
I think python 2.7 is the default installation on rhel 7, although it appears 3.3 is available.  Newer versions use scl.  If we're distributing binaries, it probably only matters for those developing cekit or those building locally.

**Comment by dbecvarik** [comment]
we need to keep python 2.7 unitil rhel 8 arrives. it is pain. but 3.x is
only from SCL :-(

we are not compiling binaries python is not compiled language :-)

**Comment by jmtd** [comment]
> we need to keep python 2.7 unitil rhel 8 arrives. it is pain. but 3.x is only from SCL :-(

Ah I see. Just checked and it's in EPEL too, but not in RHEL proper.

**Comment by dbecvarik** [comment]
lets close this and drop legacy python when RHEL 8 comes.
