### ISSUE TITLE
Documentation Improve explanation of test dependency installation

### ISSUE THREAD

**Issue by ryanemerson** [cekit/cekit#286]
Currently the [section](http://docs.cekit.io/en/develop/installation.html#test) detailing the installation of cekit is very light on details about the dependencies required for running `cekit test`. It would be great if a short explanation was added as to why these dependencies are not installed as part of the standard `dnf install` etc, as well as more detailed instructions as to what needs to be installed.

More attention could be brought to the fact that the test phase requires additional dependencies by referencing this in the opening paragraph of the parent section, i.e. http://docs.cekit.io/en/develop/installation.html#installing-cekit

**Comment by goldmann** [comment]
I think this should be now covered by merging the #355 PR. Please review the documentation about [installing Cekit](http://docs.cekit.io/en/develop/installation.html) and especially the [depednencies section](http://docs.cekit.io/en/develop/installation.html#dependencies) of it.

If $SUBJECT still requires some love, let me know. I'll close the ticket for now.
