### ISSUE TITLE
Add support for zip resources

### ISSUE THREAD

**Issue by rcernich** [cekit/cekit#31]
I'm not sure how important this is, but I think it would be nice to add support for zip resources that would be extracted as part of their retrieval.  This would be useful for using github releases as opposed to cloning the repository.  I'm sure there are other use cases that might be interesting too.

**Comment by dbecvarik** [comment]
Its nice idea - so it should work for every url?  What compression do we want to support? What about integrity checks? We probably will check zip file autenticity only, right?
* Zip is native to python so it can work without external deps i think. 
* tar, gzip, bzip2 and others can be tricky as they can require external deps.

**Comment by goldmann** [comment]
I would propose to park this feature until we get a strong use case for it.

**Comment by jmtd** [comment]
> Zip is native to python so it can work without external deps i think.

the exact sub-features of ZIP supported by Python differ between platforms. LZMA support is only included if you install the LZMA module which is not installed by default on RHEL (or OS X, but is at least available in RHEL, package pyliblzma).  DEFLATE should work everywhere though. Not sure about other ZIP features. I think LZMA-compressed ZIPs are rare in the wild.

**Comment by rcernich** [comment]
No problem parking it; just an idea.  Implementation-wise, I'd just extend the UrlResource to do the unzip, as it already handles http, https and file schemes.  The alternative would be to use UrlResource as-is and add a "zip" scheme (not sure how you register custom schemes in Python).  (ZipResource seems better to me.)

**Comment by rnc** [comment]
Closing this as there has been no demand in 4 years. We can always reopen if required.
