### ISSUE TITLE
Applying modules individually breaks support for content sets

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#340]
After merging #329 building images with defined content sets stopped working. It looks that if the sections required to content sets work are added as part of overrides, these are ignored, since these are not merged into the descriptor.

@rcernich Any idea how you want to proceed with this having in mind the change you applied?

**Comment by goldmann** [comment]
The descriptor here is passed before applying overrides: https://github.com/cekit/cekit/blob/5507a933a36b9e158b4c9e5e6680c447fad50c5a/cekit/generator/base.py#L55

**Comment by rcernich** [comment]
Overrides for the image are now applied in `Image.apply_image_overrides()`, which is where all the overrides for the image are now applied.

**Comment by goldmann** [comment]
Fixed via #341.
