### ISSUE TITLE
release notes for cekit releases

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#349]
It would be good to write short release notes for cekit releases, so it's easy to see what has changed since the last release (w/o relying on constructing a "git log" command and reading the results!)

**Comment by goldmann** [comment]
You mean this https://github.com/cekit/cekit/releases ?

**Comment by jmtd** [comment]
> You mean this https://github.com/cekit/cekit/releases ?

That's exactly it, yeah. it would be nice if those notes are exposed somewhere on cekit.readthedocs.io and/or in the image sources too, but it's good enough that they exist at all.
