### ISSUE TITLE
Define and describe CEKit development process

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#369]
It should contain information what should be done to do the release, step by step. If required, improvements to the release scripts should be applied too.

Besides this information about branches, merges, labels should be also there.

**Comment by goldmann** [comment]
Release documentation should include:

* Information about documentation generations and setting the active version on readthedocs.io
* Release notes publishing
* Blog post

**Comment by goldmann** [comment]
We need also add information how to prepare environment to be able to contribute to Cekit.

**Comment by rnc** [comment]
It should describe from the base level of settng up the environment (e.g. a virtualenv, installing the correct packages), how to run the tests, through to running a sample build to ensure everything is working as it should be.

**Comment by rnc** [comment]
Related ? #266

**Comment by rnc** [comment]
From 367 : "http://docs.cekit.io/en/develop/descriptor/image.html#labels refers to https://github.com/projectatomic/ContainerApplicationGenericLabels which is out of date."

**Comment by rnc** [comment]
While a lot of the dev process is now documented, the release process (encapsulated in https://gist.github.com/goldmann/55166f34e15d94e1433f3b305fde12a5 ) needs documenting as well.

**Comment by rnc** [comment]
As #691 added an improved release process (with subsequent PR of #691, #694, #697) I'm closing this.
