### ISSUE TITLE
docs for RHEL suggest yum-plugin-copr, doesn't exist

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#374]
unfortunately yum-plugin-copr does not exist in EPEL 7 (I think)

https://mirrors.ukfast.co.uk/sites/dl.fedoraproject.org/pub/epel/7/x86_64/Packages/y/

**Comment by goldmann** [comment]
Good catch, I was actually fooled by the https://docs.pagure.org/copr.copr/how_to_enable_repo.html documentation. I'll update it.
