### ISSUE TITLE
--build-osbs-release, -user, -nowait, etc. should imply build-engine=osbs (or fail)

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#379]
specifying `--build-osbs-release` is a no-op if you do not specify `--build-engine=osbs`

I think it should either set the build engine, or fail the build for any other build engine

same for the other `--build-engine-*` parameters

principle of least surprise :-)

**Comment by goldmann** [comment]
I think this fits into https://github.com/cekit/cekit/issues/364 and in genera into the https://github.com/orgs/cekit/projects/3 project.

**Comment by jmtd** [comment]
Yes it sounds like it fits; it's a concrete example of a UX problem with the current approach that a new approach should hopefully address.

**Comment by goldmann** [comment]
Agree. I'm not happy with the CLI and I plan to review it prior 3.0 and possibly rewrite.

**Comment by jmtd** [comment]
I need to revisit these specific options now 3 is out

**Comment by goldmann** [comment]
Yah, I think this bug is no longer relevant with the new CLI.

**Comment by goldmann** [comment]
Closing, after 3.0 and the CLI rewrite it is not an issue anymore.
