### ISSUE TITLE
Docs dependencies

### ISSUE THREAD

**Issue by rnc** [cekit/cekit#384]
Currently the Makefile (running in Fedora 29) requires use of `sphinx-autobuild`. In F29 this is a python2 dependency (python2-sphinx-autobuild). To make it consistent this should be `sphinx-autobuild-3` which comes from python3-sphinx-autobuild.

Note however that within Fedora port-for is currently 0.4.6 but sphinx-autobuild has it pinned to 0.3.1. There is an outstanding PR to fix this in https://github.com/GaretJax/sphinx-autobuild/pull/72

**Comment by goldmann** [comment]
@rnc Isn't this finished? Can you link the PR here and close it if this is the case?

**Comment by rnc** [comment]
Fixed by #395
