### ISSUE TITLE
Add support for supplementary dist-git items

### ISSUE THREAD

**Issue by AntStephenson** [cekit/cekit#394]
We have a use case for committing another yaml file for CVP (gating.yaml) which would currently be ignored by cekit, is it possible to add capabilities within cekit to define a list of supplementary items that would be synced to the dist-git at runtime? Or at the very least, support this additional file like with content_sets.yaml.

Thank you!

**Comment by goldmann** [comment]
As I mentioned earlier, this is an interesting request. I think it would be valuable to make it possible we just need to think what would be the best way to define the files, as well the target locations for them. 

Currently the `container.yaml` and `content_sets.yml` are special files that are related to the build process in OSBS with native support in Cekit. We could go that route with the `gating.yaml` file, but it would be nice to get some input from others as well. Implementing support for `gating.yaml` should be fairly easy. Adding support for arbitrary files could be harder.

**Comment by goldmann** [comment]
The simplest implementation would be:

```groovy
// pseudocode
if (fileFound('gating.yaml')) {
  copyToDistGitRoot('gating.yaml')
}
```

**Comment by goldmann** [comment]
@rnc @jmtd @luck3y @iankko What are your thoughts?

**Comment by jmtd** [comment]
@goldmann I wondered about a more generic mechanism, but I haven't sketched out a solution. Some kind of "just copy these files into the image sources" . Then I wondered how different that was from artefact handling, and whether we could use or extend that mechanism for this.

**Comment by luck3y** [comment]
+1 from me, I'd just added gating.yaml to dist-git manually before I'd read this ;)

TBH, I'm not clear on what makes the files 'arbitrary'. If they're in the github repo, don't they end up in dist-git? I'm sure I'm missing something here.

**Comment by AntStephenson** [comment]
@luck3y IIUC if the files are not explicitly handled by cekit (and subsequently referenced in your image yaml) it will not copy them, as an example for copying content_sets.yaml:

`packages:`
`content_sets_file: content_sets.yml`

**Comment by luck3y** [comment]
@AntStephenson Yeah, I get that part, I think to better rephrase my question, 'Why don't we just copy whatevers in the src directory into dist-git.' I mean that would cover it, wouldn't it?

This is the part where I'm missing something I think ;)

**Comment by goldmann** [comment]
@luck3y This could be possibly dangerous - it could accidentally overwrite some files in dist-git.

What we currently do is that we copy all files in the `target/image` directory to dist-git. This is a generated directory. One solution to support arbitrary files would be to set up some convention and agree that, for example: content of the `dist` directory (if existing) would be copied to the `target/image` directory after generation and later commited to dist-git when the osbs builder would be selected.

This way we would not need to define anything in the schema and have control from where files will be fetched and where these will be placed.

Comments?

**Comment by luck3y** [comment]
@goldmann Ah, sure I get the danger side of it, though you'd see those in the diff I image.

I like the compromise of the dist directory and just adding whatever is in there, so +1 from me.

**Comment by goldmann** [comment]
Let's schedule it for 3.1 initially since the 3.0 bucket is pretty full ATM.

**Comment by jakubschwan** [comment]
@goldmann Can be increased priority of this issue and also milestone. In QE we need these changes for CVP. We need to be able push gating.yaml file to dist-git repo automatically.

**Comment by goldmann** [comment]
An usable workaround would be to push these files manually to dist-git. These do not change often. This is what we used previously and this will work, Cekit will not remove them. Let me know if this works for you.

**Comment by jakubschwan** [comment]
Manual push is something that actually block us, we do not want to do it for every minor release. There is also huge risk that this can be forgotten with every new minor release.

**Comment by goldmann** [comment]
@AntStephenson @jakubschwan @luck3y @jmtd Could you guys take a look at #519 and let me know what you think about the implementation?

Should we make the directory name (currently `dist`) configurable? If yes - where, in image descriptor? I do not want to over-complicate this, if possible. I'm happy to change the directory name, if you have better suggestions than the currently used `dist`.
