### ISSUE TITLE
Allow --network=host option

### ISSUE THREAD

**Issue by crobby** [cekit/cekit#396]
I'm attempting to do a build with cekit, but some of the repositories are inside my VPN.  When the build container tries to resolve those repositories, it fails.  The same build succeeds if I take the Dockerfile that results from a cekit generate and do a "docker build --network=host ....".

Given that, I think it would be useful if there were a way to force the build to use --network-host.

**Comment by goldmann** [comment]
Hmm, this shouldn't be required at all. I constantly build images with repositories available only on VPN and everything just works as it should. Maybe there is some Docker configuration issue? Maybe DNS is not working properly for you?

**Comment by crobby** [comment]
I think I found *my* issue.  Somehow my /etc/resolv.conf was missing the proper nameserver entries for the VPN.  Closing this issue.
