### ISSUE TITLE
package manager should possibly be selected via image.yaml / module yaml

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#400]
Thanks to #328 we have `--package-manager`, but since the correct package manager is a property of the image being built, rather than the builder environment (running cekit), it should probably be something that can be put in a module or `image.yaml` property.

**Comment by goldmann** [comment]
I guess this also touches #364 since we need to ensure if it makes really sense to have the `--package-manager` switch.

**Comment by goldmann** [comment]
I would like to ask @ruromero who created the initial PR what are his thoughts about this issue.

**Comment by ruromero** [comment]
Moving this functionality to modules is a reasonable alternative because it is in the same place as the `from` attribute.

**Comment by luck3y** [comment]
+1 on this, would be nice to have this in image.yaml

**Comment by goldmann** [comment]
Scheduled for next release.

**Comment by goldmann** [comment]
Proposed fix in PR #431.
