### ISSUE TITLE
Artifact download performance improvment?

### ISSUE THREAD

**Issue by luck3y** [cekit/cekit#455]
Currently when artifacts are downloaded the following happens https://github.com/cekit/cekit/blob/develop/cekit/descriptor/resource.py#L210

Which is 1024 bytes at a time. Changing this to 1MB (1048576 bytes) gives a good speedup when reading from brew.

EAP 6.4.0 (~ 158MB)
Size        |  Time
1024       |  Ages (5-7 minutes, sometimes longer)
1048576 |  1:06
 
I was tempted to make this configurable, but I don't think its worth it, changing the default to 1MB seems reasonable.

**Comment by goldmann** [comment]
Agree, scheduled. Thanks!
