### ISSUE TITLE
cekit installation docs page does not exist

### ISSUE THREAD

**Issue by pavankjadda** [cekit/cekit#457]
I am looking for other platforms installation guide, now I can not it because 
[https://cekit.readthedocs.io/en/develop/installation.html](https://cekit.readthedocs.io/en/develop/installation.html) gives **  This page does not exist yet. ** error. Please fix this.

**Comment by rnc** [comment]
Note that you are looking at the development version there ; if you look here you'll find the page https://cekit.readthedocs.io/en/develop/installation/index.html
Are you wanting the current release?

**Comment by pavankjadda** [comment]
Got it. It appears link in the https://cekit.readthedocs.io/en/latest/ website is broken. It points to http://cekit.readthedocs.io/en/develop/installation.html instead of https://cekit.readthedocs.io/en/develop/installation/index.html

**Comment by goldmann** [comment]
Right, this is an oversight, but I'm not sure if it's worth fixing it. We're close to release 3.0, I would probably suggest reading the 3.0 docs either case unless you want to start right awy with CEKit :)
