### ISSUE TITLE
Add sha512 to the list of accepted hash algorithms

### ISSUE THREAD

**Issue by elmiko** [cekit/cekit#471]
**Describe the solution you'd like**
I would like to see a `sha512` field added to the [image artifact descriptors](https://cekit.readthedocs.io/en/develop/descriptor/image.html#artifacts). The value for this field would be a sha512 sum, all lowercase, with no spaces or linebreaks.

**Additional context**
I am currently encountering a situation where an upstream project (Apache Spark) that distributes only pgp signatures and sha512 sums with current releases. Our team is using cekit to build our images and we would like to continue to support this security feature without needing to manually calculate hash sums in a different manner than the upstream.

**Comment by elmiko** [comment]
i browsed the code in this repository and saw the references about the various hash algorithms, but i don't see any implementation for the actual checksum checks. i don't know too much about how cekit works, but i gather there might be a backend that is wrapped by this project, i understand that sha512 might not be supported.

if i have missed something in the code, my apologies.

**Comment by goldmann** [comment]
Thanks for the ticket!

We reuse `hashlib` module to provide this and it looks like `sha512` is supported there, so I do not see any reason why we couldn't add support for it.

```
$ python
Python 2.7.15 (default, Oct 15 2018, 15:26:09) 
[GCC 8.2.1 20180801 (Red Hat 8.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import hashlib
>>> hashlib.algorithms
('md5', 'sha1', 'sha224', 'sha256', 'sha384', 'sha512')
>>> 
```


Here is the relevant code in CEKit:

https://github.com/cekit/cekit/blob/45cab4657e3c925762dc33299ee5268b45b4e26e/cekit/crypto.py#L1-L17

**Comment by elmiko** [comment]
haha, i should have looked harder. i guess i didn't realize you were using the names from that list as keys to hashlib.

i'll take a look at working up a pr =)

**Comment by goldmann** [comment]
@elmiko Let me know if you need any help with it. We are going to cut a release very soon (next week maybe), it would be good to have this PR ready sooner than later :)

**Comment by elmiko** [comment]
will do @goldmann !

**Comment by goldmann** [comment]
Fixed in https://github.com/cekit/cekit/pull/475.
