### ISSUE TITLE
Add progress report when adding files to cache using cekit-cache command

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#482]
**Describe the solution you'd like**
It would be great to have some progress bar or something like this.

**Additional context**
None.

**Comment by goldmann** [comment]
We should not rely on external libraries, if possible.

**Comment by rnc** [comment]
Related: #78

**Comment by rnc** [comment]
While external libraries might increase overhead I think its more sensible to use something that is well developed and stable. For instance https://github.com/tqdm/tqdm provides everything that is needed and is simple to use.

**Comment by rnc** [comment]
It is actually possible to use Click's progress bar as well ( https://click.palletsprojects.com/en/8.0.x/api/?highlight=progress#click.progressbar ) **but** it is a fairly simplistic implementation and for anything more sophisticated/reliable they point to tqdm ( https://github.com/pallets/click/pull/1986/files )

**Comment by rnc** [comment]
Click:
```
2021-09-07 09:35:05,252 resource.py:285        DEBUG Downloading from 'http://download.hosts.prod.upshift.rdu2.redhat.com/devel/candidates/middleware/eap/JBEAP-7.4.1.GA-CR1/jboss-eap-7.4.1.GA-CR1-patch.zip' as /home/rnc/.cekit/cache/1f85b63e-eca2-49be-9eb5-014c51f63a1c
jboss-eap-7.4.1.GA-CR1-patch.zip  [####################################]  100%
```

TQDM:
```
2021-09-07 08:41:21,093 resource.py:283        DEBUG Downloading from 'http://download.hosts.prod.upshift.rdu2.redhat.com/devel/candidates/middleware/eap/JBEAP-7.4.1.GA-CR1/jboss-eap-7.4.1.GA-CR1-patch.zip' as /home/rnc/.cekit/cache/c0bf1be2-5e9e-4e0a-b9d0-01b782c419ac
jboss-eap-7.4.1.GA-CR1-patch.zip:  12%|████████████▌                 | 13.0M/107M [00:03<00:23, 4.14MB/s]
```

Note that neither supports outputting _via_ the logger though there is a current PR in TQDM to work towards that.

**Comment by goldmann** [comment]
Since we use Click, I vote to use Click's ability to display progress. Adding a dependency is not always easy + there are maintenance costs (RPM changes, etc). I think simple is better than nothing :)
