### ISSUE TITLE
Handle UBI built-in repositories

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#483]
**Describe the solution you'd like**
Currently the UBI images ship with a set of enabled repositories, but these repositories do not exist yet. Refreshing the metadata fails with an error preventing the image to build.

**Comment by jmtd** [comment]
Maybe the content_sets handling code should delete all existing repo files? The warning it prints "The image has ContentSets repositories specified, all other repositories are removed!" is a little confusing already, if you don't know that when it's talking about repositories it doesn't mean yum repo files in the image, but rather other possible repositories stuff in the image yaml

**Comment by goldmann** [comment]
This is not affecting CEKit only, internal systems, such as OSBS are having same issue.

The proposed solution in OSBS is to rewrite the .repo file from the image to point to internal Pulp repos. After GA these repositories will became available and there will be no issue.

So, to reiterate - there is a problem between now and GA date for local builds. For internal OSBS builds this will not be an issue. After GA this issue will not exist for local builds either.

**Comment by jmtd** [comment]
> So, to reiterate - there is a problem between now and GA date for local builds. For internal OSBS builds this will not be an issue. After GA this issue will not exist for local builds either.

The wider issue — base image has repos defined that should be ignored due to content sets, but aren't — exists for other contexts, too, though, e.g. RHEL image built on top of Fedora builder:

```
STEP 4: RUN yum makecache
Loaded plugins: ovl, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 To enable Red Hat Subscription Management repositories:
     subscription-manager repos --enable <repo>
 To enable custom repositories:
     yum-config-manager --enable <repo>
Error: error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin container=oci] Command:run Args:[yum makecache] Flags:[] Attrs:map[] Message:RUN yum makecache Original:RUN yum makecache}: error while running runtime: exit status 1
```

**Comment by goldmann** [comment]
This should be closed now since UBI is GA.
