### ISSUE TITLE
Allow cekit  to build images from scratch

### ISSUE THREAD

**Issue by spolti** [cekit/cekit#487]
**Describe the solution you'd like**
Discuss the possibility to allow cekit to build images from scratch;
Apparently that is not possible since during Dockerfile generation a few steps requires a user (Mostly root). i.e. when removing the /tmp/artifacts directory.

**Additional context**
Add any other context about the feature request here.

**Comment by goldmann** [comment]
Thanks for this ticket, I think it should be possible to add support for building images from scratch. This could be a special case and some conditionals could definitely help.

**Comment by goldmann** [comment]
I just added it to 3.1 milestone, so that it is scheduled, but I don't promise to make it part of 3.1. I think there are many corner cases that needs to be checked before we can safely say that we support it.

**Comment by spolti** [comment]
Thanks for looking on this Marek, I really appreciate.
Please let me know if I can help with something else.

**Comment by ppatierno** [comment]
@goldmann what's the status of this? We have to generate an image from "scratch" for the release of our product.

**Comment by goldmann** [comment]
Good news, I found a solution for this RFE and I'm working now on implementing it.

**Comment by ppatierno** [comment]
It's not a good news ... it's an awesome news! :-)

**Comment by spolti** [comment]
Awesome Marek, thanks :)

**Comment by gallettilance** [comment]
Hi all,  is there an ETA for feature completeness? where is this work being tracked?

**Comment by goldmann** [comment]
Hey @gallettilance, I just came back from my PTO. This is the tracker for this work. I do not want to throw any dates here just now, but I image next 2 weeks is a possible timeframe.
