### ISSUE TITLE
Local Docker build does not preserve version tags after squashing

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#488]
**Describe the bug**
When a Docker image is squashed, the version tag is not applied to the image and the `latest` tag is used.

**To reproduce**
```yaml
name: "submarine-image-real-name-on-overrides-file"
version: "1.0"
from: "centos:latest"
```

Overrides

```yaml
name: "kaas-springboot-centos-s2i"
description: "Platform for building KaaS based on SpringBoot"
```

Result

```bash
$ docker images
REPOSITORY                                                                                        TAG                               IMAGE ID            CREATED             SIZE
kaas-springboot-centos-s2i                                                                        latest                            36256fca1401        39 seconds ago      285 MB
```

**Expected behavior**
Version tag should be applied.

**Comment by goldmann** [comment]
@spolti I tried to reproduce it locally, but I couldn't:

Build log:

```
2019-04-18 09:40:10,748 cekit        INFO     Removing old 14043c7387f4 image...
2019-04-18 09:40:10,752 cekit        INFO     Image removed!
2019-04-18 09:40:10,752 cekit        INFO     Done
2019-04-18 09:40:10,772 cekit        INFO     Image built and available under following tags: kaas-springboot-centos-s2i:1.0, kaas-springboot-centos-s2i:latest
2019-04-18 09:40:10,772 cekit        INFO     Finished!
```
Images:
```bash
$ docker images
REPOSITORY                                                                                       TAG                                                                            IMAGE ID            CREATED             SIZE
kaas-springboot-centos-s2i                                                                       1.0                                                                            23765882917e        10 seconds ago      200 MB
kaas-springboot-centos-s2i                                                                       latest                                                                         23765882917e        10 seconds ago      200 MB
```

I suspect that you do not use the latest release, but some pre release. Could it be true?

**Comment by spolti** [comment]
I don't know if is the latest version, yesterday I upgrade my fedora from 28 to 29 and installed cekit with dnf install cekit.

cekit --version
3.0.dev0

A dnf update day that is nothing to update.

**Comment by goldmann** [comment]
The reason is that packages are now not even in updates-testing repository. It takes a while. https://cekit.io/blog/2019/04/cekit-3.0.0-released/ see the "How to get it?" section. I suggest you install it directly using the build mentioned on the update page. For your convenience here is the link: https://kojipkgs.fedoraproject.org//packages/cekit/3.0.0/1.fc29/noarch/cekit-3.0.0-1.fc29.noarch.rpm

**Comment by goldmann** [comment]
If you test it and it works for you, please add some karma: https://bodhi.fedoraproject.org/updates/FEDORA-2019-35c2440206 This will significantly make it faster in stable.

**Comment by spolti** [comment]
Sure thing, I'll update it as you suggested and test again, thanks. :)

**Comment by spolti** [comment]
Working after update. thanks.

**Comment by goldmann** [comment]
Awesome, I'm closing this issue in this case.
