### ISSUE TITLE
Add support for building images without modules

### ISSUE THREAD

**Issue by rcernich** [cekit/cekit#49]
For simple images, it would be nice to be able to build an image without having to write all the details out into a separate file.  Currently, there are two problems that prevent this:
1. The ``modules`` folder is always copied.  We should always create a modules folder or check to see if it exists before adding the copy command (former seems easier).
2. There needs to be a way to add local scripts into the modules folder.  This seems trickier as we can't just copy the root folder containing the image.yaml, as this can create a recursive copy into itself.  One possible option is to create a special "content" element specifically for image.yaml

**Comment by goldmann** [comment]
It's a nice idea, but we need to discuss in more details how developing of simple images should look. Let's park this idea for now.

**Comment by rcernich** [comment]
I think this also relates to the auto scanning of a local ``modules`` directory, as I suspect that's why we would want to do that (for _simple_ images).

**Comment by goldmann** [comment]
Yah, we discussed it very briefly today but we stopped since we would like to define what a simple image is and how the development workflow should look and what should be required and what not.

**Comment by rcernich** [comment]
I think I've got an example.  Hopefully, I can have something by eod.

**Comment by rcernich** [comment]
This is now working in the referenced PR.  It simply adds a "source" field to image.yaml.  It also expands image.yaml to include support for the "execute" element.

Also, I really don't think we should be automatically adding a local modules repository.  I'll create another issue.

**Comment by rcernich** [comment]
A simple example https://github.com/rcernich/concreate/blob/image-source/image.yaml#L29-L33 which includes all files/folders that are siblings of image.yaml.

**Comment by dbecvarik** [comment]
There is issue with including all siblings - imagine repo where you have your sources and image.yaml in root - we should not copy everything to image as image.yaml was not designed to be a module - if we have simple 
our sources section could be same syntax as .gitignore

``` yaml
source:
  - my_module_dir/*
  - myscript.sh
execute:
  - script: myscript,sh
  - script: my_modudule_dir/foo.sh
```

**Comment by rcernich** [comment]
That's fine, but in the case of the concreate image, it builds the python package and thus needs all the source at the root of the repository.  As far as best practices, I agree, but there's nothing that prevents using "." as the source folder.

As far as filtering goes, if we don't do this, especially with the target/output folder, we run the risk of recursively copying the target folder into the target folder, which could cause space issues on disk.

**Comment by dbecvarik** [comment]
Yes. we can add source . (I would prefer regex syntax here so .* - but that's detail) 
I also think we should copy everything - we should not ignore any directories in the code as is https://github.com/rcernich/concreate/blob/6a7f2c2c406fe149e92778d6baf0ff7987e46290/concreate/generator.py#L50

**Comment by rcernich** [comment]
I can confirm that copying ./target does cause issues as it recursively copies itself into itself.  Not filtering it will cause issues.

Regarding the module repositories, there's no reason to copy those, since they're copied over already.  I think it's OK to not filter the repositories, but theoretically, it's unnecessary, since the resources there should be specific to the modules and not the image.

**Comment by dbecvarik** [comment]
yes - copying target doesn't make sense, that's true. But target is a directory concreate create - its kind of different to others. And if you specify "source .*" I think it means copy everything in image dir (with exception of target - but that only coincidence of running concreate next to the image.yaml)
Copying local modules can create issues - but we should not try to detect them.

**Comment by goldmann** [comment]
Because of lack of use cases for it and demand I'm going to close this ticket.
