### ISSUE TITLE
yum makecache

### ISSUE THREAD

**Issue by luck3y** [cekit/cekit#501]
Currently, in a base image, if the default .repo file in /etc/yum.repos.d/ contains invalid content (yes, I know it shouldn't) the initial `yum makecache` will fail the image build. The problem occurs before any user scripting can take place (rm'ing the invalid repo file, for example), so its a bit of a problem in some cases.

An easy, but perhaps problematic solution, is to try and run it as `yum makecache || true` and continue regardless, thereby allowing the injected odcs repos (if present) and subsequent user scripting to do the right thing later. If no injected repos are present the build will fail at the package installation phase anyway.

This is more of an item for discussion rather than a concrete suggestion for a fix, but there are situations where something like this could be useful.

cc: @jmtd

**Comment by goldmann** [comment]
Other possible option would be to remove the `makecache` call entirely. This shouldn't hurt at all since the cache would be built either case on first package install.

**Comment by luck3y** [comment]
Yeah, thought about that too, but didn't know if that was going to far. +1 from me though.

**Comment by jmtd** [comment]
I created #503 to work around this same problem but this might be cleaner. I'm just testing it.

**Comment by goldmann** [comment]
Let's remove creating the cache upfront entirely.

**Comment by goldmann** [comment]
Currently scheduled for 3.1.0. If you think it should be released earlier, because it blocks you, please let me know!
