### ISSUE TITLE
tool/mode to read in  and convert a Dockerfile

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#511]
**Describe the solution you'd like**
I was thinking about how an existing project might choose to adopt cekit. Assuming they had a Dockerfile, they would need to convert this into image.yaml + modules by hand. It would be interesting if instead they could run a tool to read in a Dockerfile and generate image.yaml (+modules perhaps, for e.g. separate RUN commands?)

**Additional context**
This would be a tool people would run once and would require stuff that the rest of cekit doesn't (e.g. Dockerfile parsing) so might make sense as a separate tool.

**Comment by goldmann** [comment]
This would require having a Dockerfile parser. If I remember correctly, there is one already written by the project atomic team, but I'm not sure where it lives.

Saying this, I'm not necessarily eager to implement this as part of CEKit. AS you mention, this could be some external tool contributed and maintained by the community.

But this idea guided me towards another one: creating a skeleton for container image. This **could be** part of CEKit, for  example as `cekit-init` (or similar) command. This would make it easier to get started with it from scratch.

**Comment by goldmann** [comment]
I'm going to reject this idea for now. If there will be someone willing to take over it and prepare a PR, I'll review it. For now, closing.
