### ISSUE TITLE
Add a new option to only validate the image and module descriptors

### ISSUE THREAD

**Issue by spolti** [cekit/cekit#551]
**Describe the solution you'd like**
Add a new option to validate only the image and module descriptors to find, for example, syntax errors, invalid values, etc.

Today the --dry-run option will perform all steps that the conventional build commands does, but not build the image.

**Additional context**
A validate option would be very useful to use in a CI environment where er can't use Red Hat internal resources.

**Comment by goldmann** [comment]
I think this is a valid proposal. The "generate" phase could be divided into two:

1. Validation - this would require fetching all the modules and composing the object model. Validation is done as part of creating the model.
2. Generation - where the model is translated into format required by the builder.

We could probably even do 3 stages:

1. Preparation - fetching all the stuff
2. Creating model - which implies validation
3. Generation

Let's schedule it.

**Comment by goldmann** [comment]
@spolti Look what I have here: https://github.com/cekit/cekit/pull/555
