### ISSUE TITLE
zsh completion does not work

### ISSUE THREAD

**Issue by errantepiphany** [cekit/cekit#554]
**Describe the bug**
- cekit command completion in the zsh shell does not work. After typing "cekit " and then a tab, instead of the list of possible cekit command options being presented, one gets the current list of sub directories.

**To reproduce**
1. `sudo dnf install cekit cekit-bash-completion cekit-zsh-completion`
2. `zsh (if not already in zsh shell)`
3. `cekit <space> <tab>`

**Expected behavior**
- A list of possible cekit command options should appear.

**Logs**
- N/A

**Environment information:**
- OS: Fedora release 30 (Thirty) x86_64
- Kernel: 5.1.12-300.fc30.x86_64
- Shell: zsh 5.7.1
- CEKit version: 3.1.0

**Additional context**
- bash completion works as expected.

**Comment by goldmann** [comment]
Thanks for this report!

It works when you run this: `source /usr/share/zsh/site-functions/_cekit` and then you try to autocomplete. I'm investigating now why it isn't picked up automatically.

**Comment by goldmann** [comment]
I think the reason is that the format of the autocompletion file for ZSH used for autoloading is different from what we provide. This needs further investigation.

**Comment by errantepiphany** [comment]
**Unrelated**, but just FYI, docker has completion issues too...

I installed docker with this, which seems to come OOTB with **bash** completion:
`sudo dnf install docker`
The file ended up here, and works fine.
`/usr/share/bash-completion/completions/docker`

However I installed this for **zsh** completion:
`sudo dnf install docker-zsh-completion
The file ended up here, and does _not_ work (even if you manually source it, it returns a non-zero error code):
`/usr/share/zsh/site-functions/_docker`
Although using this plugin _does_ seem to work:
https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/docker

Just thought I'd share. Sorry for polluting this issue.

**Comment by rnc** [comment]
Does it need `#compdef cekit cekit-cache` at the top?

**Comment by rnc** [comment]
Adding something like `(( ! $+commands[cekit] )) && return 1` should fix the error handling

**Comment by rnc** [comment]
@goldmann @errantepiphany  If that works for you I can make a PR

**Comment by goldmann** [comment]
> Does it need #compdef cekit cekit-cache at the top?

Tried it already, it doesn't work. This is a required header for these files, we don't have it. My feeling is that the format of the auto-generated. content is not suitable for direct use for auto-enabled completion files in ZSH. Most probably it needs to be rewritten.

**Comment by goldmann** [comment]
Added to 3.3 release, we need to fix it because it's inconvenient and possibly not that hard to fix.

**Comment by rnc** [comment]
@goldmann Thats curious, that fixes it for me. Weird!

**Comment by goldmann** [comment]
Maybe I failed somewhere, how did you test? Did you update the `/usr/share/zsh/site-functions/_cekit` file and test it in a new terminal?

**Comment by rnc** [comment]
After discussions offline we established the confusion was because Marek is using oh-my-zsh which has different zcompdump files / configuration. Reading https://gist.github.com/ctechols/ca1035271ad134841284 gave some hints about `compinit -d $ZSH_COMPDUMP` and also removing any existing `.zcompdump*` files. This then worked.
