### ISSUE TITLE
mixing use of JSON and YAML is confusing

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#574]
I have only just noticed this! but, we use YAML most of the time (in image descriptor, in module definitions etc.) but the argument to `--override` is JSON. This is a strange inconsistency!

**Comment by goldmann** [comment]
You **can** specify YAML content on CLI too, but it would be very inconvenient. Since YAML is a superset of JSON we can use both, without any problems.

Personally I don't think this is a problem.

@rnc What do you think about it?

**Comment by rnc** [comment]
Is there anything in tests/docs using YAML on CLI or is it all JSON ? I don't have any strong opinion on it tbh, perhaps if it was documented then this would be sufficient.

**Comment by goldmann** [comment]
@rnc It's all JSON for it's CLI convenience. I'm cool with adding a note to documentation. We should add a test for YAML in CLI as well in this case.
