### ISSUE TITLE
Support specifying OSBS koji target in descriptor

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#591]
**Describe the solution you'd like**
It would be great if I could specify the koji target for a build in the descriptor (likely in an override) instead of just on the command line via `--koji-target`. Something like:

``` yaml
osbs:
  koji:
    target: some-target-here
```

I don't know if it make sense to have `osbs.koji.target` or `osbs.koji_target`.

**Additional context**
When performing a scratch development build, I already override the `osbs:` key in order to specify a different `dist-git` branch (`private-…`), but I have to remember to vary the command-line by dropping `--release`, which is intuitive, and remembering the correct value of `--koji-target`, which is not intuitive.

**Comment by goldmann** [comment]
I think it makes sense, I'll schedule it for next release. At the same time I'm going to deprecate `--koji-target` switch, because it will be redundant with the overrides mechanism. It will be removed entirely in 3.6.

**Comment by goldmann** [comment]
Removal of `--koji-target` switch is tracked here: #601.
