### ISSUE TITLE
Build CEKit for EPEL 8

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#604]
**Describe the solution you'd like**
EPEL 8 was released some time ago, we need to make CEKit available there.

**Comment by goldmann** [comment]
Initial build was kicked, it failed because of missing dependencies.

https://koji.fedoraproject.org/koji/buildinfo?buildID=1362935

```
DEBUG util.py:585:  BUILDSTDERR: No matching package to install: 'PyYAML'
DEBUG util.py:585:  BUILDSTDERR: No matching package to install: 'python3-colorlog'
DEBUG util.py:585:  BUILDSTDERR: No matching package to install: 'python3-pykwalify'
DEBUG util.py:585:  BUILDSTDERR: Not all dependencies satisfied
DEBUG util.py:585:  BUILDSTDERR: Error: Some packages could not be found.
```

**Comment by goldmann** [comment]
An update for python-pykwalify was submitted: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-83cc3520c1

**Comment by goldmann** [comment]
A PR for python-colorlog was added to build it in EPEL 8: https://src.fedoraproject.org/rpms/python-colorlog/pull-request/2

**Comment by goldmann** [comment]
Updated update to python-pykwalify: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-cf95acfbb6

**Comment by goldmann** [comment]
Contacted PyYAML maintainers with question about availability of PyYAML in EPEL 8 (the Python 3 version).

**Comment by goldmann** [comment]
PyYAML is available. Now it looks that python-docopt is missing, requested `epel8` branch, will submit a PR for review to maintainer.

**Comment by goldmann** [comment]
Update submitted: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-34493eae99

**Comment by rnc** [comment]
Closing as recent builds are also done on EPEL8 (e.g. https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2021-2d31282320 )
