### ISSUE TITLE
Make s2i builds on tests not print everything as ERROR

### ISSUE THREAD

**Issue by spolti** [cekit/cekit#605]
**Describe the solution you'd like**
When you do a s2i build on tests scenarios, all messages from s2i build are printer as error:

> 2019-08-30 14:19:08,753 - root - ERROR - I0830 14:19:08.753430   21525 sti.go:711] [INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ assembly-issue ---
> 2019-08-30 14:19:08,783 - root - ERROR - I0830 14:19:08.783657   21525 sti.go:711] [INFO] Downloading from central: https://repo1.maven.org/maven2/org/apache/maven/surefire/maven-surefire-common/3.0.0-M3/maven-surefire-common-3.0.0-M3.pom
> 2019-08-30 14:19:09,091 - root - ERROR - I0830 14:19:09.090878   21525 sti.go:711] [INFO] Downloaded from central: https://repo1.maven.org/maven2/org/apache/maven/surefire/maven-surefire-common/3.0.0-M3/maven-surefire-common-3.0.0-M3.pom (9.7 kB at 30 kB/s)

**Additional context**
Add any other context about the feature request here.

**Comment by goldmann** [comment]
I would love to have this fixed, but it's not possible. It's a bug upstream. I've opened a ticket about this in 2015... https://github.com/openshift/source-to-image/issues/156

**Comment by goldmann** [comment]
I'm marking this ticket as upstream. There is nothing I can do in CEKit here, so I'm going to close this one. Please make some noise in the linked ticket.
