### ISSUE TITLE
Add support for APK package manager

### ISSUE THREAD

**Issue by cvgaviao** [cekit/cekit#609]
**Describe the solution you'd like**
I would like to use Cekit to build images using Alpine Linux as its base image. But Alpine uses APK as its packages manager that currently is not supported by Cekit.

**Comment by goldmann** [comment]
Thanks for this report! It should be doable to add support for Alpine fairly easy, I hope. Let me investigate it. I'll schedule it afterwards.

**Comment by goldmann** [comment]
Scheduling for next release.

**Comment by goldmann** [comment]
Sadly, I need to move this into next release. It looks like there is big demand to release 3.5 very soon and I still haven't finished the PR for this ticket. It's in works, but there are a few things that needs to be ironed still. Moving to 3.6.

**Comment by goldmann** [comment]
This change will require switching from `bash` to `sh` for executing module scripts, but I don't think this will affect anyone, because in almost all cases sh is a symlink to bash.

CentOS 7:

```
[root@d82648b51043 bin]# ll /usr/bin/sh
lrwxrwxrwx. 1 root root 4 Aug  1 01:09 /usr/bin/sh -> bash
```

Fedora 30:

```
[root@fa99bdfa171a /]# ll /usr/bin/sh
lrwxrwxrwx. 1 root root 4 May 13 12:18 /usr/bin/sh -> bash
```

UBI 8:

```
bash-4.4# ls -hal /usr/bin/sh
lrwxrwxrwx. 1 root root 4 Jan 14  2019 /usr/bin/sh -> bash
```

Alpine 3.10:

```
/ # ls -hal /bin/sh 
lrwxrwxrwx    1 root     root          12 Aug 20 10:30 /bin/sh -> /bin/busybox
```

Alpine is a new kid on the block so it doesn't count :)
