### ISSUE TITLE
cekit verbose output relating to "execute" script should be adjusted

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#616]
**Describe the bug**

cekit complains about a missing "name" key with the execute/script descriptor options, but the docs do not describe any such key: https://docs.cekit.io/en/latest/descriptor/module.html#execute

**To reproduce**

Given some module with an execute key such as

```
execute:
  - script: foo.sh
```

cekit (with -v) will complain (as in the logs section below). 

**Expected behavior**

No message generated

**Logs**

```
2019-09-16 15:54:22,095 cekit        DEBUG    No value found for 'name' key in the execute section of the 'jboss.container.openjdk.jdk' module; using auto-generated value: 'jboss.container.openjdk.jdk/configure.sh'
```

**Comment by rnc** [comment]
@jmtd Is this still an issue ?

**Comment by jmtd** [comment]
Yes this is still the case with 3.6.0 at least

```
2021-02-18 16:22:25,692 cekit        DEBUG    No value found for 'name' key in the execute section of the 'jboss.container.maven' module; using auto-generated value: 'jboss.container.maven/configure.sh'
```

**Comment by rnc** [comment]
@jmtd Looks like it was me :-) It was added from #198.

And looks like the docs need updating as while a module descriptor (https://docs.cekit.io/en/latest/descriptor/module.html#name) *does* have a name, it says its required where there should be note regarding auto-generation.

**Comment by rnc** [comment]
Actually, reexamining that I'm wondering whether that is correct now... will investigate...

**Comment by rnc** [comment]
Even `ports:` have similar code which leads to descriptors internally having an object value of 
```
{'value': 8080, 'name': 8080}
```
(which doesn't seem right...)

**Comment by rnc** [comment]
Ok, so for other uses they are used internally to merge dicts. I would guess it got dragged into the 198 issue by accident so simply removing the logging should be sufficient.

**Comment by jmtd** [comment]
Thank you. I noticed another place: if you define a module source as just a path eg

```
modules:
  - path: /goo
 ```
