### ISSUE TITLE
Modules should use name instead of git repository name + ref

### ISSUE THREAD

**Issue by jfdenise** [cekit/cekit#621]
We need the directory containing the features (copied to target/test) to be deterministic and not bound to the kind of module repo acces (GIT vs local file system).

The name of the module should be used when creating the directory.

An example usage in the feature file :
https://github.com/wildfly/temp-eap-modules/blob/EAP7-1216/tests/features/7/CD/security_domains.feature#L121
The scripts we are copying are there:
https://github.com/wildfly/temp-eap-modules/tree/EAP7-1216/tests/features/7/scripts
They are located inside the features dir of the module, so copied to the
target/tests dir.
It works when we use a local file system path for the jboss-eap-modules
but fails when GIT is in use:
https://github.com/wildfly/temp-openshift-image/blob/EAP7-1216/image.yaml#L38

**Comment by goldmann** [comment]
Let's schedule it for next release, I'll take a look at the code shortly to understand why exactly we see it.
