### ISSUE TITLE
microdnf fails when passing --setopt=tsflags=nodocs

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#637]
Hi,

With microdnf=3.0.1-3.el8 (latest version available in ubi8 right now), microdnf behaves strangely when supplying `--setopt=tsflags=nodocs`, as is the default in the cekit jinja template:

```
[root@6443f6637153 /]# microdnf --setopt=tsflags=nodocs install -y unzip tar rsync shadow-utils
(process:10): librhsm-WARNING **: 16:09:11.044: Found 0 entitlement certificates
(process:10): librhsm-WARNING **: 16:09:11.047: Found 0 entitlement certificates
(process:10): libdnf-WARNING **: 16:09:11.047: Loading "/etc/dnf/dnf.conf": IniParser: Can't open file
Downloading metadata...
Downloading metadata...
Downloading metadata...
Package                                                                                                                                          Repository                                               Size
Installing:                                                                                                                                                                                                  
 libsemanage-2.9-1.el8.x86_64                                                                                                                    ubi-8-baseos                                         168.8 kB
 rsync-3.1.3-6.el8.x86_64                                                                                                                        ubi-8-baseos                                         413.7 kB
 shadow-utils-2:4.6-8.el8.x86_64                                                                                                                 ubi-8-baseos                                           1.3 MB
 tar-2:1.30-4.el8.x86_64                                                                                                                         ubi-8-baseos                                         858.4 kB
 unzip-6.0-41.el8.x86_64                                                                                                                         ubi-8-baseos                                         197.3 kB
Transaction Summary:
 Installing:        5 packages
 Reinstalling:      0 packages
 Upgrading:         0 packages
 Removing:          0 packages
 Downgrading:       0 packages
Downloading packages...
Running transaction test...
[root@6443f6637153 /]# echo $?
141
```

This fails builds. One workarounds seem to exist: don't pass `--setopt=tsflags=nodocs`, although that (might) mean that behaviour is different (not sure that microdnf is even honouring this)

This might get fixed in microdnf itself, although I haven't filed it there yet. But the lead time on getting that fix deployed would likely be quite long, and rule out us using the ubi8-minimal images for some shorter-term projects. So I'm filing this wondering what you might think about working around it in cekit?

**Comment by luck3y** [comment]
As a possible workaround we could install dnf as the first package and then use that, though this reduces some of the differences between minimal and full. We'd need some indication or a pre-run script as a cekit module to do this though, as cekit won't understand that it begins with package manager A and then switches to B.

**Comment by jmtd** [comment]
upstream microdnf bug https://bugzilla.redhat.com/show_bug.cgi?id=1769831

**Comment by spolti** [comment]
Without removing the flag it also failed while installing only the dnf package.

**Comment by goldmann** [comment]
@spolti Does it mean that the proposed workaround by @jmtd (not passing `--setopt=tsflags=nodocs`) does not work?

**Comment by goldmann** [comment]
Ah, now I understand. The workaround is still valid, it's just that we cannot work with @luck3y's workaround. One solution would be to add a module that would use microdnf command to install dnf, and not as packages.

**Comment by goldmann** [comment]
Upstream microdnf issue: https://github.com/rpm-software-management/microdnf/issues/50

**Comment by spolti** [comment]
@goldmann correct, the workaround that Ken suggested will not work. So far the only one that apparently works is removing the nodocs flag.

**Comment by jmtd** [comment]
I guess we could stop using nodocs and do a post-install "rm -rf /usr/share/doc"  or similar

**Comment by jmtd** [comment]
This was resolved in microdnf at some point; the issue is not present in microdnf-3.4.0-1.el8.x86_64 (
