### ISSUE TITLE
Provide a container image containing CEKit

### ISSUE THREAD

**Issue by rimolive** [cekit/cekit#639]
**Describe the solution you'd like**
Gitlab CI uses container images to run pipelines and we'd like to use CEKit. Although we can create our own image, it would be good having a "official" image for it.

**Additional context**

**Comment by rnc** [comment]
Given the complications of what should the image provide, what should it be based upon, I think this may be better served if we do better on keeping the RPMs up-to-date (which is being worked on in #754) and therefore would make it far easier for someone to create their own custom image (which could be based on rhel,fedora,ubi etc) and install CEKit from the RPM.

**Comment by goldmann** [comment]
I agree with @rnc here. We tried to provide such container image in the past, but we hit issues related to not provided deps and the solution was to create a custom image either case hence the suggestion to use RPM (or pip directly!) and create own container image, if needed.

I'll close this ticket now.
