### ISSUE TITLE
Add support for defining artifact sources

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#644]
**Describe the solution you'd like**
It should be possible to specify together with artifact information about the source used to build this artifact. This information could be used later to generate a tarball/image with sources.

**Additional context**
https://docs.cekit.io/en/latest/descriptor/image.html#artifacts schema needs to be altered to accommodate this request. For artifacts that are built in Brew (plain artifact definition) we could potentially try to find the source and generate proper `koji-fetch-url.yaml` file.

For other types of artifacts, if the source information is not provided, we should print a warning.

Everything should be applied only if the `--redhat` flag is used.

**Comment by rnc** [comment]
There seems some cross-over to the work done in #661 which would allow the source container work to construct the appropriate sources. Whether CEKit should support this _as well_ is another question...

**Comment by rnc** [comment]
As this will be superseded by `fetch-artifacts-pnc.yaml` (See https://github.com/containerbuildsystem/atomic-reactor/pull/1590 ) which will provide OSBS the ability to capture sources I am closing this.
