### ISSUE TITLE
Test - Running container with custom entrypoint

### ISSUE THREAD

**Issue by cescoffier** [cekit/cekit#659]
This is more a question than a request for enhancement.

I'd like to run some test with something like:

```
Scenario: Check if quarkus user is correctly configured
    Given container is started with entrypoint sh   
    Then run sh -c 'id' in container and check its output for id=1001(quarkus) gid=1001(quarkus) groups=1001(quarkus)
```

The tested container has a defined `entrypoint` and die immediately. So I can run any command, but I would like to check the internals of the container, like the check given above. For this, I would like to change the entry point to be `sh`, which would allow me to run commands.

I've done an attempt to implement my own step:

```python
@given(u'container is started with entrypoint sh')
def step_impl(context):
    client = docker.from_env()
    container = client.containers.run(image=context.config.userdata['IMAGE'], entrypoint="sh")    
    context.containers.append(container)
```

But it does not work. It seems that behave can't find it (the file is `./tests/steps/entrypoint_steps.py`). In addition, I don't know Python, which is always interesting... 

Anything that I can do to replace the entrypoint?

**Comment by luck3y** [comment]
The steps it uses are here: https://github.com/cekit/behave-test-steps/blob/v1/steps/container_steps.py which are downloaded or you can point to your own repo with --test-steps I think it is.

There is a variant of what you're trying to do in there now:

https://github.com/cekit/behave-test-steps/blob/v1/steps/container_steps.py#L289

You should be able to run this with sh and then execute whatever commands you want.

**Comment by cescoffier** [comment]
Thanks @luck3y! 

I forked the repo and implement my missing step with my most beautiful python (ok... maybe not). 
Do you want a PR or is this feature too specific?

**Comment by luck3y** [comment]
@cescoffier Sounds generally useful to me, really up to @goldmann though.

**Comment by goldmann** [comment]
Sure, open a PR!

**Comment by cescoffier** [comment]
I will! Thanks for the help!
