### ISSUE TITLE
Add support for Cachito

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#663]
**Describe the solution you'd like**
https://osbs.readthedocs.io/en/latest/users.html#fetching-source-code-from-external-source-using-cachito

When the artifact type would be used, this would be added to the Dockerfile:

```
COPY $REMOTE_SOURCE $REMOTE_SOURCE_DIR
```

We should clean up the `$REMOTE_SOURCE_DIR` at the end.

It should be supported only on OSBS.

**Comment by goldmann** [comment]
Once this is done, it would be good to create a new document that explains how multi-stage builds with golang and cachito should work together: https://docs.cekit.io/en/latest/handbook/index.html.

**Comment by goldmann** [comment]
We could also add new switch to the OSBS builder: `--with-cachito` that would modify the generated Dockerfile. This would be probably much cleaner implementation.

**Comment by rnc** [comment]
So currently CEKit already supports the `container.yaml` file ( https://docs.cekit.io/en/latest/descriptor/image.html#osbs-configuration ) where the cachito configuration is stored (https://osbs.readthedocs.io/en/latest/users.html#fetching-source-code-from-external-source-using-cachito) so by detecting that we can probably activate the integration without the need for any new flags.

**Comment by rnc** [comment]
PR : https://github.com/cekit/cekit/pull/665
