### ISSUE TITLE
Invalid 'execute' key not caught by 'image.yaml' validation

### ISSUE THREAD

**Issue by abkieling** [cekit/cekit#664]
**Describe the bug**
Adding invalid `execute` key in image descriptor isn't caught by 'image.yaml' validation.

**To reproduce**
Execute a script directly from `image.yaml`.

**Expected behavior**
Expected CEKit to fail fast due to invalid YAML and inform the reason.

**Logs**
```
STEP 1: FROM registry.redhat.io/ubi8/go-toolset AS builder
STEP 2: USER root
STEP 3: COPY             unpacked_remote_sources             /workspace/
STEP 4: USER 
Error: error building at STEP "USER ": USER requires exactly one argument
2020-12-02 08:04:41,859 cekit        ERROR    Image build failed, see logs above.
```

**Environment information:**
 - Fedora 33
 - CEKit version: 3.7.0

**Additional context**
The invalid `execute` key was added to the first stage of a multi-stage build.

**Comment by rnc** [comment]
Are you able to give me the invalid file please to aid in reproducing the exact problem?

**Comment by abkieling** [comment]
Unfortunately not. Just the following to an `image.yaml` file:
```
execute:
  - script: build.sh
```
