### ISSUE TITLE
additional arguments to package manager (specifically microdnf and --setopt=install_weak_deps=0)

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#668]
**Describe the solution you'd like**

I would like the invocations to microdnf generated by cekit in response to `packages:` values to include the extra command-line argument `--setopt=install_weak_deps=0`.

This causes microdnf to not install recommended or suggested RPMs ("weak" dependencies), only traditional "requires" ones. This will result in generally smaller images.

The only way to configure microdnf to do this is via command line, it is not possible to influence it via configuration file or similar: https://github.com/rpm-software-management/microdnf/blob/8a1f065966362afb96e95d177d829271a3ee3ab7/dnf/dnf-main.c#L176

**Additional context**

the last respin of the openjdk containers grew in size by 6% as a result of transitive weak package dependencies.

**Comment by goldmann** [comment]
@rnc FYI

**Comment by rnc** [comment]
@goldmann @jmtd Should we make this change to `microdnf` to be the hardcoded default or a flag? From the ticket, I think the request is for the former - potentially changing the template (etc) to add this.

**Comment by jmtd** [comment]
Thanks for working on this so quickly!

I had started to sketch out an idea of how I would implement this in my head if I did it (looks like you will move faster though ;)) - I'd add a configuration variable `packages.manager.flags` which defaulted to `--setopt=tsflags=nodocs `. The template would simpify down to `{{ pkg_manager }} {{ pkg_manager_flags }} -y install…`. To add what I want, I'd specify

```
packages:
  manager: microdnf
    flags: --setopt=tsflags=nodocs --setopt=install_weak_deps=0
```

In theory this would simplify `template.jinja` and also give people a way of overriding `--setopt=tsflags=nodocs`, or setting any other flags they want. However, it might not be that simple, there might not be a globally-suitable default value for that parameter, since `--setopt=tsflags=nodocs` is not appropriate for `apk`. So the default value of the parameter I propose here would need to actually be looked up in a dict of supported package managers, which might be a little bit too magic. Except: that's effectively what your PR is doing already ,and the logic that handles the `apk` case (in the template, not in the helper) ignores the new parameter anyway.

So: my shower-thoughts idle design work aside, your PR looks (eyeball test only) to do what I want, at least :)

**Comment by rnc** [comment]
@jmtd Thats an interesting set of suggestions! Currently it looks like the `tsflags=nodocs` is a hidden option that is not documented. **If** we think adding that option is an acceptable compromise _for now_ I would vote to also document the two options in that associated PR and merge.
