### ISSUE TITLE
Add GitHub CEKit Action to docs

### ISSUE THREAD

**Issue by rnc** [cekit/cekit#671]
Reference: https://github.com/manusa/actions-setup-cekit

**Comment by rnc** [comment]
cc @manusa

**Comment by rnc** [comment]
@manusa Do you have any example repos where this is being used please?

**Comment by manusa** [comment]
We're using it here https://github.com/jkubeio/jkube-images to create the base images for [Eclipse JKube](https://github.com/eclipse/jkube).

Unfortunately I haven't seen this action used [elsewhere](https://github.com/search?l=YAML&q=manusa%2Factions-setup-cekit&type=Code).
