### ISSUE TITLE
Missing flexibilty to change the image tag in case of multi-stage build

### ISSUE THREAD

**Issue by Kaitou786** [cekit/cekit#689]
**Describe the solution you'd like**
Hi, we wanted to have flexibility on giving the tag of the generated runtime-image. We tried with the `overrides` but it changes the `name` on both the image and leads to the error at build time:
So doing  `cekit -v  build --overrides "{'name': "my_image"}"  docker` gives 
```
CekitError("Image build failed: 'invalid from flag value operator-builder: pull access denied for operator-builder, repository does not exist or may require 'docker login': denied: requested access to the resource is denied'"))
```
The `operator-builder` is the image that is given to the first/builder image in the descriptor,
seeing the docker logs, the override seems to be working first at the builder image but when artifact is being copied to runtime image the old reference of image is used:
```
Step 1/26 : FROM golang:1.14 AS my_image
Step 19/26 : COPY --from=operator-builder /workspace/manager 
 ```
**Additional context**
Add any other context about the feature request here.

**Comment by rnc** [comment]
Apologies for not replying sooner. This is actually supported as per documented in https://docs.cekit.io/en/latest/handbook/building/builder-engines.html#podman-builder 

You can pass in your Makefile e.g.
```
# Build the docker image
docker-build:
	cekit -v build $(BUILDER) --tag ${IMAGE}
# Push the docker image
docker-push:
	$(BUILDER) push ${IMAGE}
```

On my machine (using the 1.4.0 tag from your kogito-operator repository) I then see:
```
podman images
REPOSITORY                                   TAG         IMAGE ID      CREATED         SIZE
quay.io/kiegroup/kogito-cloud-operator       1.4.0       159a1d7d05b7  38 seconds ago  152 MB
```

in contrast to the original Makefile which produces:
```
podman images
REPOSITORY                                   TAG         IMAGE ID      CREATED             SIZE
localhost/operator-runtime                   1.0.0       740c244b7079  About a minute ago  152 MB
localhost/operator-runtime                   latest      740c244b7079  About a minute ago  152 MB
quay.io/kiegroup/kogito-cloud-operator       1.4.0       740c244b7079  About a minute ago  152 MB
```

If this isn't sufficient please let me know.
