### ISSUE TITLE
Allow the use of CEKit on host distributions which have no odcs clients

### ISSUE THREAD

**Issue by stephengaito** [cekit/cekit#696]
**Describe the solution you'd like**

Allow the use of CEKit on host distributions (such as Debian/Ubuntu) which have no odcs clients.

Add a command-line/configuration option to allow/disallow the use of odcs content_sets (and hence the dependency check noted below).

**Additional context**

The ``Generator.dependencies`` (in the ``generator/base.py`` file) has a *hard* dependency on the ``python3-odcs-client`` python module (which, at the moment, only seems to be available on RedHat derived distributions).

On distributions which have no odcs clients *and* in CEKit descriptions which do not use ``content_sets`` this *hard* dependency stops CEKit from being used for no good reason.

**Comment by rnc** [comment]
We run our GitHub CI on Ubuntu (https://github.com/cekit/cekit/blob/develop/.github/workflows/cekit.yml) and I have tried installing a Ubunutu VM and while I did have to `pip install odcs` I did manage to get it to work. Can you clarify please, have you installed all requirements from the Pipfile and what error are you seeing?

**Comment by stephengaito** [comment]
@rnc

Ah brave new world!  (alternatively... you are forcing a rather old dog to learn new tricks.... hey ho)

I can see from a systems architect's point of view that ODCS will be a very nice (possible) future.
Alas, I can not see it being usable on Debian distro's for a wee while...

I have done some more investigation and find that the odcs python package can be installed on all of my Ubuntu machines with relatively little difficulty.... so I will admit simply installing it (and not using it) is easier than making major changes to your code... as such I have closed PR #698 

**However** I find that since you *do* have a hard requirement on the python odcs package in your code, both the ``requirements.txt`` and ``Pipfile`` files are *incorrect*.  They should both have ``odcs>=0.3.2`` in their *runtime*  (and not their *development*) requirements sections.

I am in the process of creating a new Pull Request to fix these problems.

---

**Many many thanks for creating such a cleanly developed and useful project!**

(I have at least two privately developed versions of cekit and I am more than happy to retire them and use an external open source package!  Your code is well structured!)

**Comment by stephengaito** [comment]
@rnc , You asked to see what error message I was getting:

```
dev@cpDev ~/t/cekit> cekit build podman
2021-03-21 08:35:01,457 cli.py:296        WARNING You are running unreleased development version of CEKit, use it only at your own risk!
2021-03-21 08:35:01,459 tools.py:235        WARNING You are running CEKit on an untested platform: Ubuntu 20.04.2 LTS (Focal Fossa). External dependencies suggestions will not work!
2021-03-21 08:35:01,460 tools.py:365        WARNING The certifi library (https://certifi.io/) was found, depending on the operating system configuration this may result in certificate validation issues
2021-03-21 08:35:01,461 tools.py:367        WARNING Certificate Authority (CA) bundle in use: '/etc/ssl/certs/ca-certificates.crt'
2021-03-21 08:35:01,634 builder.py:72         INFO  Generating files for podman engine
2021-03-21 08:35:01,634 base.py:64         INFO  Initializing image descriptor...
2021-03-21 08:35:01,635 cli.py:345        ERROR Required CEKit library 'odcs-client' was not found; required module 'odcs' could not be found.
```
Using the ``image.yaml``

```
name: my-example
version: 1.0
from: debian:stable-slim
description: test on ubuntu without odcs

packages:
  manager: apt-get
  install:
    - python3-minimal

```
This is on a clean KVM based on a recent Ubuntu focal (using libvirt). Using the commands:

```
    cd
    git clone https://github.com/cekit/cekit.git
    sudo pip3 install /home/dev/cekit
    cd /home/dev/tmp/cekit
    cekit build podman
```
Note that the ``sudo pip3 install /home/dev/cekit`` did *not* install the ``odcs`` python package (since it is not a run-time dependency in your current ``develop`` branch).

The relevant code (in the file ``cekit/generator/base.py``) is:
```
    @staticmethod
    def dependencies(params=None):
        deps = {}

        deps['odcs-client'] = {
            'package': 'python3-odcs-client',
            'library': 'odcs',
            'rhel': {
                'package': 'python2-odcs-client'
            }
        }

        if CONFIG.get('common', 'redhat'):
            deps['brew'] = {
                'package': 'brewkoji',
                'executable': '/usr/bin/brew'
            }

        return deps

```
I hope this helps!

**Comment by rnc** [comment]
All credit to @goldmann for the clean design :-) Thanks for the excellent reproducer and clear diagnosis; we'll take a look.

**Comment by rnc** [comment]
@stephengaito I think this is solved now with #701 so can be closed?

**Comment by stephengaito** [comment]
@rnc 

Yes I will confirm that the most recent cekti/cekit develop branch works very nicely on an Ubuntu (focal) machine in the wild ;-)

Many many thanks for an excellent tool, as well as all your help getting these PR's through the system.

**Comment by goldmann** [comment]
Thank you very much for your contributions @stephengaito!

**Comment by jmtd** [comment]
Sadly this was unfixed in #727 and so ODCS remains a hard-dependency for CeKit. [I'm looking at packaging CeKit for Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1055584) so I've come up against this. I'd like to avoid packaging ODCS for Debian as a dependency. Really, ODCS is *not* a real dep for CeKit, since you can perform many/most operations without it.

I haven't looked closer (yet) at why ODCS needed to be re-introduced as a dep in 2021 but I believe it related to readthedocs? I will check whether the reasoning then still holds today.
