### ISSUE TITLE
do not automatically add local "modules" repository

### ISSUE THREAD

**Issue by rcernich** [cekit/cekit#70]
I really think repository definitions should be explicit.  It doesn't really save any effort (two lines max in image.yaml) and hides part of the logic in the tool (i.e. users need to know the tool will look for a local modules folder collocated with the image.yaml).

Additionally, I don't like the fact that we name the local repository "modules."  Something like "modules.local" might be more descriptive and less likely to have naming conflicts.

**Comment by dbecvarik** [comment]
I more or less agree.
Its better to not do magical things.

**Comment by rcernich** [comment]
I should add that with #49, there's no real reason to do this for simple images, e.g. standalone/basic product images, as a separate module would no longer be required (i.e. you'd only have to use modules for more complex images or cases where you want to share modules across multiple images).

**Comment by dbecvarik** [comment]
This is not happening anymore. Closing it.
