### ISSUE TITLE
`extra_dir` doesn't remove files from git repo

### ISSUE THREAD

**Issue by tchughesiv** [cekit/cekit#700]
**Describe the bug**
`extra_dir` doesn't clean up missing files, it only adds new files or makes changes to existing ones.

**To reproduce**
use `extra_dir` w/ cekit 3.9.0, remove a file from the directory and run a second build.

**Expected behavior**
The files pushed to git repo should exactly match the most current file structure in a local `extra_dir`... meaning non-existent files should be removed via git.

for example, w/ `release 1.0` we have a dir that looks like this
```
fileA
fileB
```
cekit copies both files to dist-git, but then we have `release 2.0`which looks like this
```
fileB
fileC
```
but dist-git looks like this
```
fileA
fileB
fileC
```
when it should look like `release 2.0`
```
fileB
fileC
```

**Environment information:**
 - RHEL 8
 - CEKit version: 3.9

**Comment by rnc** [comment]
Related #683

**Comment by rnc** [comment]
@tchughesiv Do you have an example of your images files please?

**Comment by tchughesiv** [comment]
**To reproduce**
From the root of https://github.com/kiegroup/kie-cloud-operator, run make bundle-scratch.
The configuration is here -
https://github.com/kiegroup/kie-cloud-operator/blob/0b3b2b44383ba2db8d4e5eb4a37b8673c07396c9/hack/go-build-bundle.sh#L59-L61

The file we're experiencing the issue is here -
https://github.com/kiegroup/kie-cloud-operator/blob/d730dd40c3127a8c2f8e5f53b742a9d632234bf0/deploy/olm-catalog/prod/7.11.0-1/manifests/businessautomation-operator.7.11.0-1.clusterserviceversion.yaml

With each new bundle version, a different version of that clusterserviceversion.yaml is added. The old one should be removed. Hmm... thinking through this some more, for now anyway, i _might_ be able to just start naming that file the same every time. Maybe `businessautomation-operator.clusterserviceversion.yaml`. Still though, this is an issue that is sure to crop up in the future. As it stands a user will have to be vigilant about cross-checking what's been placed in dist-git.
