### ISSUE TITLE
Add optional copy to extra_dir functionality

### ISSUE THREAD

**Issue by rnc** [cekit/cekit#708]
Spawned from #684 

We should add the ability to add copy to https://docs.cekit.io/en/latest/descriptor/image.html#osbs-extra-directory e.g. `copy_extra_dir_to` to denote a target location in the image to copy the files to.

To make this easier we should change how `extra_dir` works and copy the **directory** across and not just the contents. This is a user visible change.

This will make it easier to manage and add the `COPY` instructions. It would also then make it possible to implement https://github.com/cekit/cekit/issues/700 as there is a known location to manage.

cc @AntStephenson @tchughesiv

**Comment by AntStephenson** [comment]
@spolti FYI
