### ISSUE TITLE
Newer cekit versions cannot work with older microdnf due to install_weak_deps flag

### ISSUE THREAD

**Issue by ppatierno** [cekit/cekit#714]
I notice the latest cekit versions add the `install_weak_deps` flag [1] on the execution of a `microdnf` command.
The problem is that it cannot work for building images using an older version of microdnf which doesn't support that flag yet.
For example, I was trying to use cekit 3.9 to build an image which uses as base ubi7minimal and when running, cekit raises this error:

```shell
2021-04-03 15:40:13,423 docker_builder.py:108        INFO  Docker: Step 7/21 : RUN microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y unzip tar rsync shadow-utils             && microdnf clean all             && rpm -q unzip tar rsync shadow-utils
2021-04-03 15:40:13,424 docker_builder.py:108        INFO  Docker: 
2021-04-03 15:40:13,562 docker_builder.py:108        INFO  Docker: ---> Running in e7aecd6d7100
2021-04-03 15:40:13,975 docker_builder.py:108        INFO  Docker: error: (--setopt) Unable to handle: install_weak_deps=0
```
Running the same command line on a ubi8minimal image works fine.
So I noticed that ubi7minimal has `microdnf-2-8.el7.x86_64` while ubi8minimal has `microdnf-3.4.0-1.el8.x86_64`; only the newer supports the `install_weak_deps` flag.
A colleague run the build using an older cekit (3.7) and it worked because it generatesd the above microdnf command in the Docker image file but without the above flag.

I was wondering if there is the possibility to disable flags for microdnf through the image descriptor; I couldn't find anything useful in the documentation but just the note "For microdnf, the flag --setopt=install_weak_deps=0 is also added.".

[1] https://github.com/cekit/cekit/blob/develop/cekit/template_helper.py#L109

**Comment by rnc** [comment]
cc @jmtd

**Comment by rnc** [comment]
Related https://github.com/cekit/cekit/issues/668

**Comment by jmtd** [comment]
> cc @jmtd

I guess we could revisit the idea of user-specified package manager flags as a key in the descriptor YAML

**Comment by rnc** [comment]
@jmtd Agreed ; by the default the flags should probably target the latest supported microdnf (for instance) - so it wouldn't affect you - but by adding the ability to override them, this would solve the backwards compatibility issue.

**Comment by ppatierno** [comment]
@rnc isn't it the other way around? By default cekit should not add flags that are in the latest release for backward compatibility and leaving the user, through the image descriptor file, a way to add new flags (i.e. the `install_weak_deps`)

**Comment by jmtd** [comment]
Another way to look at it is: should rhel7 base users expect the cutting edge releases to work OOTB, or pin an old version, or explicitly specify some metadata?

**Comment by rnc** [comment]
@ppatierno Can you point me to the yaml you are using please?

**Comment by ppatierno** [comment]
@rnc this is an example https://github.com/jboss-container-images/amqstreams-1-openshift-image/blob/amqstreams17-dev/bridge/image.yaml

**Comment by rnc** [comment]
@ppatierno For reference, the PR was to add the ability to handle older versions of microdnf on the latest releases ; we haven't fully discussed whether CEKit should, on its bleeding edge releases, target latest microdnf releases while still providing functionality for users to override who are using older versions of microdnf, or whether there it should target the lowest common denominator. 

What version of cekit are you currently using?

**Comment by ppatierno** [comment]
I am using cekit 3.9 so I discovered the issue. My colleague had to use the older 3.7 in order to handle this case with ubi7 image and older microdnf version.
Anyway, we are going to move to ubi8 image and it will be fixed by itself.
My argument was that anyway newer cekit versions broke the compatibility with older microdnf versions that worked fine until cekit 3.7.

**Comment by rnc** [comment]
Yes, I concur that we didn't realise that microdnf hadn't had support for those other setopt commands in versions used ubi7 which wasn't ideal :-(
