### ISSUE TITLE
Issues having two images in the same yaml with multiple osbs sections

### ISSUE THREAD

**Issue by AntStephenson** [cekit/cekit#719]
**Describe the bug**
When testing [Cachito integration](https://github.com/cekit/cekit/issues/711) we realised our image.yaml has two osbs sections. If we include the `remote_source` section in the first osbs block its stripped out in the second one.

**To reproduce**
Clone https://github.com/AntStephenson/rhpam-kogito-operator/tree/KOGITO-4851
Move the `remote_source` section (image.yaml L47 -> 51) to the first osbs block (L13). 

**Expected behavior**
COPY operations and such described in the Cachito integration issue should be there in the Dockerfile, and the container.yaml should contain the necessary pieces.

**Logs**
Paste any logs you have, use CEKit verbose output: `cekit -v`.

**Environment information:**
 - Operating system
 - CEKit version: Result of `cekit --version`

**Additional context**

**Comment by AntStephenson** [comment]
@rnc fyi

**Comment by rnc** [comment]
I _think_ the problem is in https://github.com/cekit/cekit/blob/develop/cekit/descriptor/image.py#L240
