### ISSUE TITLE
Add source-url and source checksum for fetch-artifacts-url

### ISSUE THREAD

**Issue by hjmodi** [cekit/cekit#720]
**Describe the solution you'd like**
Update fetch-artifacts.url.yaml automation to add source-url and source checksum to allow OSBS to build source images for middleware products

**Additional context**
Currently, there's no way to map URL to their sources since that information cannot be backtracked from the URLs. Adding source-url will help keep track of that information and allow OSBS to build source images for middleware products.

**Comment by rnc** [comment]
Closing after offline discussion - will be replaced by changes for fetch-artifact-pnc for osbs.
