### ISSUE TITLE
remote_source specified in the builder image is not added to the container.yaml

### ISSUE THREAD

**Issue by AntStephenson** [cekit/cekit#722]
**Describe the bug**
Having the remote_source in the builder image in a multi-stage build causes the remote_source block to be omitted from the container.yaml. An untested (could produce other issues?) workaround exists to add it to both osbs blocks. 

**To reproduce**
https://github.com/AntStephenson/rhpam-kogito-operator/blob/575bd53a4d8e7e7787c18dc6d79eaf985fd1b7e4/image.yaml

**Expected behavior**

**Logs**
Paste any logs you have, use CEKit verbose output: `cekit -v`.

**Environment information:**
 - Operating system
 - CEKit version: Result of `cekit --version`

**Additional context**

**Comment by AntStephenson** [comment]
@rnc here you go :)

**Comment by rnc** [comment]
This was discovered testing #719. It looks like generator/osbs.py `_prepare_container_yaml` does not handle multi-stage builds where the container configuration may be in a prior stage.
