### ISSUE TITLE
Documentation is failing to build

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#724]
**Describe the bug**
https://readthedocs.org/projects/cekit/builds/

Latest builds are failing and we don't have updated docs published.

**Comment by rnc** [comment]
I've locked colorlog to < 6 ( https://github.com/cekit/cekit/pull/725 ) as it won't be compatible with Python3.

However, readthedocs doesn't seem to pick it up ... I've tried changing the buildenv to Python3 and it seems to now work:
https://readthedocs.org/projects/cekit/builds/13530697/
https://docs.cekit.io/en/latest/

**Comment by rnc** [comment]
Huh. While it fixed that build, it didn't fix the the other one. Weird...

**Comment by rnc** [comment]
OK, I think I've narrowed it down to the ODCS changes in https://github.com/cekit/cekit/pull/701 from https://github.com/cekit/cekit/issues/696 Unfortunately, until https://github.com/readthedocs/readthedocs.org/pull/8065 is merged we can't easily add ` libkrb5-dev` which is needed. See https://readthedocs.org/api/v2/build/13537269.txt

**Comment by rnc** [comment]
Deleted temporary ISSUE724 branch.
