### ISSUE TITLE
Allow to work with variables in the image.yaml

### ISSUE THREAD

**Issue by jonathanvila** [cekit/cekit#745]
**Describe the solution you'd like**
It would be nice to expand variables inside the image.yaml : 
* pass params to the `cekit build` command 
* check env variables

**Additional context**
An image.yaml ( and other descriptor files used by cekit to build) file that contains variables placeholders like $URL , $USER, etc

**Comment by rnc** [comment]
I'm not completely convinced by this as it can lead to lots of unexpected consequences - while one developer may have `URL` defined in their environment another may not making debugging rather difficult. This could also lead to problems where unexpected expansions are being done in other developers descriptor files.

@goldmann  Thoughts?

**Comment by goldmann** [comment]
Yah, I definitely agree with @rnc here.

One possibility I would see for this is that env variable expansion would be done before CEKit processing the descriptor. This would not be provided by CEKit itself and would need to be done externally as preprocessing of image descriptors.

**Comment by rnc** [comment]
Expansion via other tooling could be done via #746 
@jonathanvila I think I'm afraid we're going to reject this.

**Comment by jonathanvila** [comment]
Definitely nick .... I created both tickets as 2 ways of getting the same.
If the stdin input is implemented, then the modifications can be done with
external tools ( sed, kustomize.... )

Thank you
