### ISSUE TITLE
Allow to load the image.yaml content from the stdin

### ISSUE THREAD

**Issue by jonathanvila** [cekit/cekit#746]
**Describe the solution you'd like**
Be able to use `sed 's/replace/original/g' myfile.yaml | cekit build docker -` , so cekit loads the descriptor from the standard input instead of only from a physical file.

**Additional context**
This will allow preprocessing without persisting changes.

**Comment by jmtd** [comment]
I think this would also permit people putting a shebang in image yamls, e.g.

```
#!/usr/bin/env cekit --descriptor /dev/stdin --other-options --blah build podman
```
