### ISSUE TITLE
RPM Builds

### ISSUE THREAD

**Issue by rnc** [cekit/cekit#754]
Currently the RPM builds are out of date and the build process is not well documented. Also the process to _obtain_ the RPMs from a user point of view is also not well documented.

We should:

- Document the build process
- Review the options for building and using automation (be it in Pagure/GitHub Actions (e.g .https://github.com/marketplace/actions/rpm-build
 )  etc)
- Review what https://github.com/cekit/packaging is used for and if unused consider archiving it.

**Comment by goldmann** [comment]
How to build and submit release in Fedora

* Fetch https://src.fedoraproject.org/rpms/cekit source
* Go to `main` branch
* Update spec file: source reference, version, dependencies (if any).
* Add source tarball to lookaside cache.
* Commit changes.
* Build for Rawhide.
* Repeat same for all supported Fedora versions and EPEL.
* Once all is built, submit a new update via https://bodhi.fedoraproject.org/

**Comment by rnc** [comment]
Possibly of interest : https://hobo.house/2017/09/03/automate-rpm-builds-from-git-sources-using-copr/

@goldmann I don't currently have permission on the CEKit src.fedoraproject.org/rpms/cekit repo.
