### ISSUE TITLE
Consider using black formatter

### ISSUE THREAD

**Issue by rnc** [cekit/cekit#765]
Use a standardised formatter such as Black (https://github.com/psf/black) or Brunette (https://github.com/odwyersoftware/brunette) (a maintained fork of Black) that supports `setup.cfg`

The main decision to be made is on line length. 
- Black uses 88 ( https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length ) 
- CEKit currently has nothing (though unused (historical) mentions in config files for 100/132) 

Product-ci-cd uses 88. Some references:
- https://hilton.org.uk/blog/source-code-line-length
- https://nickjanetakis.com/blog/80-characters-per-line-is-a-standard-worth-sticking-to-even-today

While we do have 'higher resolution' monitors nowadays there is plentiful research and standards to suggest that 80-100 e.g. the 88 standard of Black is preferred.

Thoughts? cc @goldmann @jmtd

**Comment by goldmann** [comment]
OMG. we will never close the ticket.

**Comment by goldmann** [comment]
Let's make it 88 then and see how it will go.

**Comment by jmtd** [comment]
One thing to decide is: do you reformat all the existing code at once, or not? If you do, then it will break tracing history with git blame etc. (or at least make them much harder).  If you don’t, then the linter needs to be clear enough that you can see whether the number of breaching lines is going up or down with each PR. I think the second approach is better (I really rely on git history, blame, etc to understand a code base) but I haven’t looked to see how the suggested formatter/linter work.

I’ve got no problem with 88 lines as the number picked :)

**Comment by rnc** [comment]
@jmtd All code is reformatted with this PR. It also adds a test that validates that the formatting and linting is correct.

I see what you mean but its not really possible I think with the black formatter. For me, if there is an issue that I need to track back with then e.g. IntelliJ easily allows one to step back through historical git blame annotations on a per line basis.
