### ISSUE TITLE
Consider using linter

### ISSUE THREAD

**Issue by rnc** [cekit/cekit#766]
While CEKit currently has **unused** `.flake8` and `.pylintrc` files in its git directory there is currently no automated linting. Similar to #764 and #765 we should consider using verification tooling in the standard test suite / workflow.

**Issues:**

-  pylint ( https://pylint.org/) is _very_ noisy compared to flake8 ( https://flake8.pycqa.org/en/latest/index.html )
- CEKit currently has exclusions in the source code for pylint (which are ignored as pylint is not in the standard dev container)

**Conclusion:**
Given how picky pylint is I _don't_ think we should use it as part of the test suite due to the overhead of getting it initially included. While it could be considered for future it may be easier to choose flake8 initially.

Thoughts? @goldmann @jmtd 

**References:**

- https://luminousmen.com/post/python-static-analysis-tools
- https://medium.com/proteinqure/auto-fixing-annoyances-with-black-and-pylint-56564811c031
- https://siderlabs.com/blog/about-style-guide-of-python-and-linter-tool-pep8-pyflakes-flake8-haking-pyling-7fdbe163079d/
- https://sbarnea.com/lint/black/

**Comment by goldmann** [comment]
I'm happy to use flake8.
