### ISSUE TITLE
Docker multi platform support incomplete

### ISSUE THREAD

**Issue by galderz** [cekit/cekit#775]
The initial work in #759 is not enough to use docker as a builder for multi-platform images.

Docker builder needs to call `buildx` one way or the other to be able to produce multi-platform images. Combining that with `qemu` aarch64 and other platforms beyond x86 can be supported.

The issue is that the docker python client does not have buildkit support included, so it cannot call `buildx`. See https://github.com/docker/docker-py/issues/2230

Focusing only on the docker builder, two paths seem possible:

1. If `platforms` is passed in, fallback on docker CLI rather than docker python client. E.g. https://github.com/docker/docker-py/issues/2230#issuecomment-479182823
2. Switch docker builder to using BuildKit rather than docker python client.

The first option would appear to be less cumbersome, at least as a temporary workaround.

Other alternatives, beyond the docker builder, would be to try with `podman` or `buildah`, but that's beyond the scope of this issue.

**Comment by rnc** [comment]
@galderz I agree that (1) sounds like the most straight forward option. Do you have any examples of what the CLI should be and what you are expecting please?

**Comment by galderz** [comment]
I already told @rnc, but for future reference: we ended up using `cekit` only to generate the `Dockerfile` and then call `docker buildx` from command line.
