### ISSUE TITLE
Suggestion: show some kind of download progress feedback 

### ISSUE THREAD

**Issue by jrenaat** [cekit/cekit#78]
When doing generate for large source files, the console doesn't show any feedback on progress, making it hard to establish whether the tool is working, or suffering some kind of problem instead.

**Comment by rnc** [comment]
@jrenaat Do you mean when CEKit downloads large remote URL based resources or some other action?

**Comment by jrenaat** [comment]
After 4 years, I really don't remember what I meant exactly ;)

**Comment by rnc** [comment]
Yeah sorry about that ; I've started going over older issues before I got involved :-)

**Comment by rnc** [comment]
Fixed with #751
