### ISSUE TITLE
regression: help.md not added in Dockerfile with 3.12.0 onwards

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#797]
**Describe the bug**

[For an image which has the following in its descriptor](https://github.com/jboss-container-images/openjdk/blob/ubi9/ubi9-openjdk-11.yaml#L51):

```
help:
  add: true
```

Attempting to perform an OSBS build with  cekit 4.0.0 or newer and the `help.md` file is not installed in the Dockerfile. Here's
an excerpt of the diff of the commit to dist-git that was generated:

```
@@ -273,6 +273,5 @@
     WORKDIR /home/default
     # Define run cmd
     CMD ["/usr/local/s2i/run"]
-    ADD help.md /
 ## /
 ## END target image
\ No newline at end of file
```

**To reproduce**

```
cekit --redhat --descriptor ubi9-openjdk-11.yaml build --overrides-file redhat/ubi9-openjdk-11.yaml osbs --release
```

**Expected behavior**

help.md to be generated (I think this is still happening) and instructions added to the Dockerfile to install it in the image.

**Logs**

```
🍊grep help typescript 
2022-07-05 09:46:00,726 base.py:399        INFO  Rendering help.md page from template /home/jon/cekit/4.1.1/lib/python3.6/site-packages/cekit/generator/../templates/help.jinja
2022-07-05 09:46:00,740 base.py:413        DEBUG help.md rendered
2022-07-05 09:46:04,512 tools.py:256        DEBUG Copying 'target/image/help.md' to '/home/jon/.cekit/osbs/containers/openjdk/help.md'...
2022-07-05 09:46:04,512 osbs.py:513        DEBUG Staging 'help.md'...
```

**Environment information:**
 - Operating system RHEL8
 - CEKit version: Result of `cekit --version` 4.1.1

**Additional context**

 Related issue: #504

Last working tag: 3.11.0
Tested broken: 3.12.0, 3.13.0, 4.0.0, 4.1.0, 4.1.1

**Comment by jmtd** [comment]
Looks like this hunk is the culprit

https://github.com/cekit/cekit/pull/738/files#diff-ee211c056e23bdadd346d0f5eba35980144406e39b35a16fc3224e6fa9afd49fL258

And this hunk disabled the test which would catch it

https://github.com/cekit/cekit/pull/738/files#diff-aee5da1af5e460cd5ee1dce704d249dd56704a21da20479614dad5d2ef1c6679L101

**Comment by rnc** [comment]
@jmtd I don't think this is correct - according to the OSBS docs (e.g. `guide_to_layered_image_build_service_osbs` on the source), the `help.md` should be placed in dist-git and :
> atomic-reactor will convert help.md and append an ADD instruction to the Dockerfile at build time

Can you point me to an OSBS build displaying this problem (preferably on gchat)

**Comment by jmtd** [comment]
>     atomic-reactor will convert help.md and append an ADD instruction to the Dockerfile at build time

it converts the `help.md` into a manpage (`help.1`) and ADDs that. I don't think it adds the help.md too, but I'm not sure now!

> Can you point me to an OSBS build displaying this problem (preferably on gchat)

I haven't submitted one yet (bailed once I noticed the missing help.md), but I'll do so in a minute and paste it on gchat. Thanks

**Comment by rnc** [comment]
I don't think its _meant_ to add the help.md ; just the generated man page. Could we do a scratch build to check?

**Comment by jmtd** [comment]
It looks like the driver for the upstream stuff to create or consume `/help.1` has gone away, anyway, and is gradually rotting. The `/help.1` files in my existing images are unreadable and probably hinder rather than help. I think we should just drop the whole thing!
