### ISSUE TITLE
Clarify minimum Python version

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#799]
**Describe the bug**

It's not clear from a user POV what the minimum Python version requirement is.

https://github.com/cekit/cekit/blob/develop/docs/handbook/installation/instructions.rst#L8
says ">= 3.6".

https://github.com/cekit/cekit/pull/788 says "3.6 deprecated".

And whilst testing https://github.com/cekit/cekit/pull/793 I found things didn't work with 3.6, but did with 3.9 (haven't tested in between those versions yet)

**Comment by rnc** [comment]
You are correct that document needs updating after #788 - the reason for that was Python 3.6 is EOL

**Comment by rnc** [comment]
I am currently reconsidering this and may revert #788 within #793

**Comment by rnc** [comment]
I am resolving this as Python 3.6 has been maintained and the installation instructions do mentioned 3.6.
