### ISSUE TITLE
Support maintaining repository tags for release builds 

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#809]
**Describe the solution you'd like**

We use cekit to build our container images. We publish container images from builds triggered by cekit. We would like to tag the container source repository to indicate which commits correspond to published images.

For example, if we built and shipped a container named foo which had a version: 1.0, I would like to tag the corresponding source repository commit with foo-1.0, or similar.

There are a bunch of issues here, but most fundamentally: cekit doesn't perform the release; that happens externally. So it's not as  simple as adding a tag to the `build --release` workflow. On the other hand, doing it manually (as now) opens up the risk of making mistakes, and once you've published a tag, you can't reasonably un-publish it (I've just found a mistake, which is what motivated me to finally file this enhancement request)

Perhaps cekit could create, but not push, tags in the local clone of the container sources, with a convention like "foo-1.0-candidate" or similar; leaving the user to create the real tag (`git tag foo-1.0 foo-1.0-candidate`) and push that. It would reduce the risk of mistakes at least.

**Comment by rnc** [comment]
There is the option for docker/podman/buildah to have 
```
  --tag TAG        Use specified tag to tag the image after build, can be specified multiple
                   times.
```
However that doesn't exist for OSBS just:
```
  --release                 Execute a release build.
  --nowait                  Do not wait for the task to finish.
  --sync-only               Generate files and sync with dist-git, but do not execute build.
  --commit-message MESSAGE  Custom dist-git commit message.
```

`release` denotes whether it is running in scratch mode (which isn't made explicit in the documentation). 

When you state `cekit doesn't perform the release; that happens externally` are you referring to the fact the OSBS builder runs externally? 

Assuming `no-wait` was **not** specified, given we know the branch/commit, we could after a successful build (optionally) tag the repository. We could support a similar `--tag TAG` command (or we attempt to construct a suitable tag - but that may not be in the format users wish?)

**Comment by jmtd** [comment]
Hi Nick, thanks for responding so quickly. I wasn't talking about *container image tagging*, though: I mean *git repository tagging*.

**Comment by rnc** [comment]
> Hi Nick, thanks for responding so quickly. I wasn't talking about _container image tagging_, though: I mean _git repository tagging_.

That is what I have done .... see the linked PR.

**Comment by jmtd** [comment]
Hi  @rnc, sorry for a long delay on getting back to you on this.

The tagging I was describing in this issues was *container image source code tagging*, not `dist-git` tagging. Here' a description of the image build and release process, and why this would be useful

1. developer prepares the sources for an image release version `1.0` (as specified in the image descriptor).
2. (via cekit) developer submits a build to OSBS. At this stage we don't know if the build will complete, nor what the *release* component of the built image would be, if it does complete
3. (outside of cekit) OSBS completes, a build is produced in the OSBS container image repository, e.g. `fooimage:1.0-4`.
4. (outside of cekit) the rest of the release process happens: an errata is drafted, the builds are attached to it, QE do their bit, release engineering do their bit, etc.
5. eventually (possibly) the image actually ships and customers can download it

It's not until step 5 that we can say categorically that the *image source code* that built the image that shipped to customers corresponds to the version that reaches the customer. And it's after stage 5 that we, ideally, tag the image source code repository with something like `fooimage-1.0-4` and/or `fooimage-1.0`.

We can make a guess that this code will correspond to `fooimage-1.0` right back at stage 2, although we might be wrong if anything fails between that and stage 5. However, it would be useful to mark the source code in some way at that point, perhaps with something like `fooimage-1.0-candidate`, so that when we finally ship, we can go back and retag (`git tag fooimage-1.0-canddidate fooimage-1.0 # yes, we actually shipped`)

Right now, we have to do this as a multi-step process, which is imperfect

1. image ships. check the image version metadata
2. go back to internal Brew to check artefact. what hash from dist-git was used to build it
3. go to dist-git repository and check the commit message for that hash. This will list the hash for the *image source* that populated the dist-git commit.
4. look up that hash in the image source repository. Pray that it's a commit reachable from one of the main branches and not an orphan (this can happen!)

**Comment by rnc** [comment]
We discussed this offline. In summary tagging **both** the dist-git and source repositories would be useful. However using a simple static tag might not be sufficient due to candidate rebuilds hence we should retrieve the release version (of an NVR). Further cgit only supports annotated tags so we should modify how we are tagging.
