### ISSUE TITLE
support source-url and source-md5 keys for artifacts definition

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#810]
**Describe the solution you'd like**

Given an artifacts section such as

```
artifacts:
- name: jolokia-jvm
  target: jolokia-jvm-1.6.2.redhat-00002-agent.jar
  md5: 760f2fbaf6b142192f3cee2c99bfcbf8
```

which (for the specific build types I am using) is translated into an OSBS `fetch-artifacts-url.yaml` file

```
- md5: 8b3af39995b113baf35e53468bad7aae
  target: jmx_prometheus_javaagent-0.3.2.redhat-00003.jar
  url: (redacted)
```

I wish to have additional keys in the destination file `source-url` and `source-md5`, as described in the OSBS docs (linked below).

At the moment, I can't put these in the cekit YAML as they are unrecognised keys, and I can't put them in the destination file as Cekit will over-write it.

Ideal solution is to extend the Cekit schema to copy those keys over from the artifact stanza from the descriptor YAML. But a next-best thing would be to ignore and preserve the keys in the target file when they are present.

**Additional context**

This is a necessary change to our images as part of a licence compliance issue, see https://issues.redhat.com/browse/OPENJDK-1065 (if you are a red hatter)

https://osbs.readthedocs.io/en/latest/users.html#fetch-artifacts-url-yaml

**Comment by rnc** [comment]
While I agree that the schema should probably be extended to support the new OSBS schema, I agree with @luck3y that you really should look at migrating to fetch-artifacts-koji or even better fetch-artifacts-pnc.yaml (the latter avoids any need to push to Brew).

**Comment by jmtd** [comment]
I can't see any support for fetch-artifacts-koji in cekit, am I looking in the wrong places?
fetch-artifacts-pnc would probably work for me (jolokia and prometheus agent jars). I just need to figure out some of the correct keys/values. Thanks

**Comment by rnc** [comment]
Oops. Good point, we just support -url and -pnc :-)

**Comment by jmtd** [comment]
Hi folks - I (think) I've addressed our particular requirement by adding PNC keys to the artifact definition, see https://github.com/jboss-container-images/openjdk/pull/328/files (this might be interesting to any consumers of those JARs from cct_module I guess too).

Although the wishlist item in this issue still stands, since I don't need it, I'm not advocating for it so I'll close (but if you prefer to keep wishlist issues open, even without a "customer", please re-open)

I might file a separate, minor issue: adding the `pnc_*` keys means I have to remove the `md5` key, which is a shame, since that prevents doing local dev builds not using OSBS. I might be able to use an override to fix that, not sure, since the artifact definition is in a module, not in the image descriptor.

**Comment by rnc** [comment]
I'm going to reopen this as I do think we should support the current schema (even if its not the most optimal solution)

**Comment by rnc** [comment]
I think Plain and URL based artifacts should _optionally_ support `source-url` and `source-<hash>`. Note that technically `source-md5`, `source-sha1` or `source-sha256` are supported.
