### ISSUE TITLE
Enable inclusion and exclusion of behave tests using regex

### ISSUE THREAD

**Issue by ankithbtik** [cekit/cekit#821]
**Describe the solution you'd like**
I would like to include (and also exclude) a few specific tests when I am building and testing my docker image using CEKit.

**Additional context**
Behave framework provides different ways — for ex. custom tags, or additional flags like `--include-re` and `--exclude-re` — to include or exclude a few specific tests or features for any execution. However, CEKit doesn't allow using all those flags or custom tags. 
We have a valid use case where we are building multi-arch docker image, and we want to run different integration-tests for each image. Because we are using the same image descriptor and modules, it is not possible to run different sets of tests for each image. After exploring the Behave framework, I realized that having the support of inclusion and exclusion of feature files in CEKit will solve that very common problem.

**Comment by ankithbtik** [comment]
Happy to raise a pull request for this.

**Comment by greenatatlassian** [comment]
I hadn't realised, but Behave offers this include/exclude based on regular expression through their `--include` and `--exclude` flags: https://behave.readthedocs.io/en/stable/behave.html. It seems reasonable to expose more of the Behave API in this way.

Alternately, we could further expose Behave tag expressions. Currently CEKit builds the tag expression to pass to Behave's `-t` flag internally, but we could allow users to add to this expression through a CEKit flag on the `cekit test behave` command. 

Perhaps it would be reasonable to do both?

**Comment by ankithbtik** [comment]
I have raised a PR for this: https://github.com/cekit/cekit/pull/825
