### ISSUE TITLE
Check functionality of OSBS Builder and confirm type hints

### ISSUE THREAD

**Issue by greenatatlassian** [cekit/cekit#823]
While adding type hints (#820), I noticed that the OSBS builder appears to have some serious type errors. Specifically, `self.artifacts` seems to be treated both as a list of paths (`str`) and as a list of `Resource`. Perhaps I'm not reading the code correctly, or there is some point where the type of `self.artifacts` is changed by a replacement.

I suggest we:
- Verify this code is covered by some testing (including using artifacts—existing tests may have an empty list here, in which case the code wouldn't fail even if incorrect).
- Review and update the type hints or the code as necessary to make this consistent.

**Comment by rnc** [comment]
I think `self.artifacts` **should** be a `List[str]` especially as future iterations (over e.g. `all_artifacts`) place `target` in it (which is a `str`). Or perhaps I'm missing where its a list of Resource :-) Some of the other `TODO` you highlighted look valid.
