### ISSUE TITLE
Add new fields to module.yaml envs

### ISSUE THREAD

**Issue by jfdenise** [cekit/cekit#846]
We are doing some automation that uses module.yaml. 
We would need need fields added to envs. Currently we only have name and description, we need required="true"|"false" and usage="build-time"|"execution-time".

**Comment by rnc** [comment]
We discussed this in separate chat (and with @goldmann ) and this relates to  https://docs.cekit.io/en/latest/descriptor/image.html#environment-variables The ticket #735 is slightly related as well. 
As different users may have different requirements @goldmann suggested adding a `metadata` field that a user can nest arbitrary data under.

**Comment by goldmann** [comment]
@jmtd Your approach looks cleaner. I don't know about how it could be implemented in the schema. If Kwalify would allow additional keys then I think it could be a good (better?) approach.

Regarding the counter-arguments:

1. See above.
2. Unlikely. We haven't touched this in years -- I don't think this will hit us.

**Comment by jmtd** [comment]
>  I don't know about how it could be implemented in the schema. If Kwalify would allow additional keys then I think it could be a good (better?) approach.

I can't (quickly) see a way that kwalify can do that. (It might be possible, I'm just skimming the docs briefly, but I haven't time this morning to look more thoroughly; might manage this afternoon). The current schema effectively only checks two things
* name is present and a string
* description, if present, is a string

So one approach would be not to set `self.schema`, thus skipping pykwalify checks for `env:`, and manually implement those two checks above in a Env-specific method and call it from `Env.__init__`.

**Comment by jmtd** [comment]
No sooner did I write that...
<https://pykwalify.readthedocs.io/en/master/validation-rules.html#allowempty>:
> If True, the map can have keys which are not present in the schema, and these can map to anything.

**Comment by jmtd** [comment]
This should do the trick. I'm just testing it now: https://github.com/jmtd/cekit/commit/20b55fbbf7b5fef8e6bb8015ae0747abf0059212

**Comment by rnc** [comment]
@jmtd Nice! I had just seen that as well and @goldmann pointed it out to me. You could layer on top of my existing PR if you want.

**Comment by jmtd** [comment]
> @jmtd Nice! I had just seen that as well and @goldmann pointed it out to me. You could layer on top of my existing PR if you want.

I have in this branch: https://github.com/jmtd/cekit/tree/ISSUE846-env-metadata but I haven't adjusted the test (yet)

**Comment by rnc** [comment]
@jmtd You _should_ be able to push your further commits to the existing PR branch. And the docs in that PR need updating as well I guess.
