### ISSUE TITLE
Provide support to the ARG property

### ISSUE THREAD

**Issue by spolti** [cekit/cekit#865]
**Describe the solution you'd like**
Sometimes there is a need to have a build argument to be used in a multi-stage build, as part o f the build process.

In this case, we would like to have CeKit support the usage of the ARG property in the `image.yaml` descriptor.
A simple use case can be found in this Dockerfile:

```
FROM quay.io/kiegroup/kogito-swf-builder-nightly:latest AS builder

ARG QUARKUS_EXTENSIONS

# Copy from build context to skeleton resources project    
COPY --chmod=777 * ./resources/

RUN /home/kogito/launch/build-app.sh ./resources

RUN ls -lah
RUN pwd
RUN cat /home/kogito/serverless-workflow-project/pom.xml
RUN ls -lah  /home/kogito/serverless-workflow-project/target/
#=============================
# Runtime Run
#=============================
FROM registry.access.redhat.com/ubi8/openjdk-11:latest

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --from=builder --chown=185 /home/kogito/serverless-workflow-project/target/quarkus-app/lib/ /deployments/lib/
COPY --from=builder --chown=185 /home/kogito/serverless-workflow-project/target/quarkus-app/*.jar /deployments/
COPY --from=builder --chown=185 /home/kogito/serverless-workflow-project/target/quarkus-app/app/ /deployments/app/
COPY --from=builder --chown=185 /home/kogito/serverless-workflow-project/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV AB_JOLOKIA_OFF=""
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
```

**Additional context**
Add any other context about the feature request here.

**Comment by radtriste** [comment]
`QUARKUS_EXTENSIONS` is indeed used by build-app script.
In other words, `ARG QUARKUS_EXTENSIONS` and `build-app script` are coming from the builder image (`quay.io/kiegroup/kogito-swf-builder-nightly` in our example) .

I would set them either before or after the `FROM`

**Comment by rnc** [comment]
@radtriste Is this a custom written Dockerfile? (as CEKit doesn't support arbitrary RUN commands). I am just trying to figure out how you plan to use this?

**Comment by radtriste** [comment]
With Cekit we create a builder image, It should contain ARGs and build-app script.

Then to builder the final application, we use the builder image and call the build-app script. That is what the above Dockerfile is doing.
However the ARG you see above should not be in the final Dockerfile but in the builder image directly.
For now we cannot do that with Cekit, thus the issue created.

Hope this is clear :)
