### ISSUE TITLE
OSBS: Use https:// instead of git:// protocol from now on.

### ISSUE THREAD

**Issue by Tas-sos** [cekit/cekit#869]
The `git://` protocol has already been retired for security reasons. You have to use the `https://` protocol from now on.
```bash
https://example.com/git/namespace/package
```

:warning: Please note that in addition to `https://` you have to add the suffix `/git`.

**Comment by rnc** [comment]
Reopening - turns out the protocol for Brew/OSBS should be
```
git+https://
```

**Comment by Tas-sos** [comment]
#871
