### ISSUE TITLE
[docs] Diagram does not load

### ISSUE THREAD

**Issue by userbradley** [cekit/cekit#891]
**Describe the bug**

The diagram on `https://docs.cekit.io/en/latest/getting-started/modules.html` does not load

![image](https://github.com/cekit/cekit/assets/41597815/a836d155-545c-488d-9caa-b10ecb1ca346)

**To reproduce**

Navigate to [https://docs.cekit.io/en/latest/getting-started/modules.html](https://docs.cekit.io/en/latest/getting-started/modules.html)

**Expected behavior**

A diagram is there

**Logs**

N/A

**Environment information:**

Vivaldi | 6.5.3206.63 (Stable channel) (arm64)
-- | --
Revision | 5c2593a2fee32e8ecaa6e8fc0fa3aae84c8d3413
OS | macOS Version 14.3 (Build 23D56)
JavaScript | V8 12.0.267.19
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Command Line | /Applications/Vivaldi.app/Contents/MacOS/Vivaldi --flag-switches-begin --flag-switches-end --disable-smooth-scrolling --save-page-as-mhtml
Executable Path | /Applications/Vivaldi.app/Contents/MacOS/Vivaldi
Profile Path | /Users/<>/Library/Application Support/Vivaldi/Default
Linker | lld
Variations Seed Type | Null

**Additional context**

**Comment by rnc** [comment]
Fixed in https://docs.cekit.io/en/develop/getting-started/modules.html

**Comment by userbradley** [comment]
Can confirm that page works. Having a browse around, other pages that have diagrams seem not to work as of current.

let me know if you need a list and I can try piece some together

**Comment by rnc** [comment]
> Can confirm that page works. Having a browse around, other pages that have diagrams seem not to work as of current.
> 
> let me know if you need a list and I can try piece some together

Did you browse on the develop branch? As the 'latest' branch won't be regenerated until I do the next release.

**Comment by userbradley** [comment]
I did... not. 

Looks to be working. Nice work!

**Comment by rnc** [comment]
np, thanks for the report!
