### ISSUE TITLE
Update Documentation Theme

### ISSUE THREAD

**Issue by rnc** [cekit/cekit#896]
Currently we lock the sphinx-autodocs and prevent sphinx from being upgraded. The early autodocs is now hard to setup locally due to its age. The guzzle theme is now unmaintained and incompatible with later sphinx versions. We should change from guzzle to another theme listed on e.g. https://sphinx-themes.org/#themes

On several of the themes below I have found it hard to display the caption `Container image creation tool` on the sidebar. Most themes now provide their own sidebars i.e. the template customisation, the CSS etc all may not be required.

# [Guzzle](https://github.com/guzzle/guzzle_sphinx_theme/)
This is the current theme and is rendered https://docs.cekit.io/en/develop/index.html 

It does support breadcrumbs. There is no right hand side contents. Inline contents work fine. Navigation does float when scrolling. Search does provide context.

# [Sphinx-Read-The-Docs](https://sphinx-rtd-theme.readthedocs.io/en/stable/) 
![image](https://github.com/cekit/cekit/assets/1169793/83f6236e-735d-443c-b13f-8f532a17d569)

It does support breadcrumbs. There is no right hand side contents. Inline contents work fine. Navigation does float when scrolling. Search does provide context.

# [Furo](https://pradyunsg.me/furo/)
![image](https://github.com/cekit/cekit/assets/1169793/efa99585-16c6-45a1-b10d-efb8ff2e5047)

It doesn't currently support breadcrumbs. Inline contents are not required and either need to have a special class added to them to allow them or removed (and rely on the righthand sidebar). Supports dark/light theme. Navigation does float when scrolling. Search does provide context.

# [Alabastor](https://alabaster.readthedocs.io/en/latest/)
![image](https://github.com/cekit/cekit/assets/1169793/9b6ad391-615a-4665-bf29-69259504bdfc)

Very minimal, similar to current theme.  No breadcrumbs or right hand sidebar. Does support `description` tag to add blurb under logo. It is not possible to display the CEKit version from what I can see. Navigation does not float when scrolling.

# [SphinxBook Theme](https://sphinx-book-theme.readthedocs.io/en/latest/reference.html)
![image](https://github.com/cekit/cekit/assets/1169793/f81c2869-04ff-4f2b-a900-9a06f3a57084)
Similar to Furo. Looks like it derives from https://pydata-sphinx-theme.readthedocs.io. Doesn't support breadcrumbs. Has a righthand sidebar (which effectively duplicates inline contents like Furo). Navigation does float when scrolling. Supports extra buttons like full-screen, dark/light mode. Doesn't have a footer containing links to Sphinx etc. Search does not provide context.

# [SphinxAwesome](https://sphinxawesome.xyz)
![image](https://github.com/cekit/cekit/assets/1169793/2586fc8b-ba21-4a06-87f4-5dba64aebb28)
Interesting configuration system using a proper Python object. Does support breadcrumbs. Highlighting better than most. Light/dark mode. Search has context. Annoying paragraph indicator on each heading. Screen 'flash' on every page change which is a known issue but makes using this impossible.

**Comment by rnc** [comment]
Captions on some are not styled that well. For example:

Guzzle
***
![image](https://github.com/cekit/cekit/assets/1169793/1eab572a-4829-4c78-9d1c-cee700b514c9)
***

Furo

***
![image](https://github.com/cekit/cekit/assets/1169793/a1c497ea-c803-43a4-84f9-3babafd3f721)

Actually, I think part of the problem was the pygments style interfering. Removing that and leaving at default gives the following:

![image](https://github.com/cekit/cekit/assets/1169793/2cf8d432-0576-4dd4-b3ad-cfe96e12b517)

***

RTD style is : 

***
![image](https://github.com/cekit/cekit/assets/1169793/15edbc26-cc31-4f90-b9d6-5f73c40a76ef)
***

And Book is
***
![image](https://github.com/cekit/cekit/assets/1169793/692be433-ddfd-4097-b35a-05ca5566071d)
***

**Comment by jmtd** [comment]
I think support for dark mode is a big plus. How heavily do we make use of breadcrumbs?

**Comment by rnc** [comment]
> I think support for dark mode is a big plus. How heavily do we make use of breadcrumbs?

Breadcrumbs at the top on the original I think are fairly redundant as the left hand panel also shows the path. The same panel also gives sufficient information in e.g. Furo.

**Comment by jmtd** [comment]
From what I can see I like the look of Furo. FWIW :)

**Comment by goldmann** [comment]
I'm with @jmtd, Furo++.

**Comment by rnc** [comment]
Both SphinxBook and Furo were my initial choices as well. Initially I preferring SphinxBook as its layout I thought was slightly better and had some useful extra features (such as full screen/download). However the search results producing no context is just not usable. Hence I'm now looking to see how best to customise Furo - I'll push up a very rough branch to provide a preview.
