### ISSUE TITLE
CLI: enhance commands for doing releases

### ISSUE THREAD

**Issue by slaskawi** [cekit/cekit#90]
Currently doing release is a bit confusing. It requires invoking `concreate build --build-engine=osbs --build-osbs-release`.

It would be nice if this command chain was replaced by a single one, e.g.: `concreate release`. The build engine could be inferred as well as `--build-osbs-release`.

**Comment by dbecvarik** [comment]
Even if we do release, we will have some options for it. Other release possibility would be docker push.

**Comment by goldmann** [comment]
Related to #364.

**Comment by goldmann** [comment]
CLI was redesigned, I don't think this ticket is valid anymore, closing.
