### ISSUE TITLE
post-build cleanup of /var/lib/rpm breaks rpm in resulting images

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#905]
**Describe the bug**
Because we remove `/var/lib/rpm` in clean-up (8873315469583f82fd3705d94b935f2eb494d789 , this was me) , `rpm` does not function properly in downstream images

**To reproduce**
build a redhat or fedora-based container with cekit 4.11.0 or newer.
try to run rpm in the result

```
$ docker run --rm -ti 233a9acf2623 rpm -qa java-*
error: cannot open Packages database in /var/lib/rpm
```

**Expected behavior**

e.g. 

```
$ docker run --rm -ti ubi9/openjdk-17:1.18 rpm -qa java-*
java-17-openjdk-headless-17.0.10.0.7-2.el9.x86_64
java-17-openjdk-17.0.10.0.7-2.el9.x86_64
java-17-openjdk-devel-17.0.10.0.7-2.el9.x86_64
java-17-openjdk-jmods-17.0.10.0.7-2.el9.x86_64
```

**Comment by rnc** [comment]
I think this was expected given the discussion on https://github.com/cekit/cekit/issues/886 ?

**Comment by jmtd** [comment]
I somehow missed that `rpm` would cease functioning. I think that's a big problem.

**Comment by rnc** [comment]
@ricardozanini As you raised #886 I think you should be aware of this. 
@jmtd If that directory is being left, this means the sqllite DB is then still there. Does this then mean we need back the microdnf clean commands?

**Comment by ricardozanini** [comment]
> I somehow missed that `rpm` would cease functioning. I think that's a big problem.

yeah, once we remove the directories `rpm` won't work anymore. The image is supposed to be final based on the reproducible builds approach. Although, it can potentially break new layers of using rpm.

**Comment by ricardozanini** [comment]
@jmtd I'm not using Cekit package manager, but relying on base images that already have what I need. For the other libraries, I'm using tar/untar, manual scripting to install what I need. It's a pain, but at least we can fit into the reproducible build patterns.

I'd say that you can safely revert, but I think we should think in a way to support reproducible builds in Cekit in a different issue/requirements.

**Comment by rnc** [comment]
@ricardozanini Thanks for the input. I agree with using a new separate ticket to focus on reproducible builds. If I recall @jmtd in #886 you mentioned about not removing certain dpkg directories - I imagine this is the same as the rpm scenario? Perhaps @ricardozanini you could (in a new ticket) elaborate on what else is needed for reproducible builds apart from the package manager issue? Perhaps the package manager cleanup 'type' (i.e. final using rm or partial) could be made configurable?

**Comment by ricardozanini** [comment]
@rnc I think we could start a new ticket using this as a starting point: https://github.com/reproducible-containers

More specifically: https://github.com/reproducible-containers/repro-pkg-cache

Let me know what you guys think and I can elaborate more in a new issue.
