### ISSUE TITLE
Ability to inject Args before module processing

### ISSUE THREAD

**Issue by etsauer** [cekit/cekit#915]
**Describe the solution you'd like**
I would like the ability to define `args` at the image descriptor and override level that that get defined in the Containerfile before the module sections get built out. 

A common practice for me (pre CEkit) is to use ARG statements to dynamically set certain package names or versions before installing packages, and have them consumed as follows:

```
ARG OPENSSL_PKG="compat-openssl11"

...

RUN dnf -install -y ${OPENSSL_PKG} ...
```

This allows me to more easily change package names when I switch FROM images between slightly different builds, like ubi ro ubi-minimal or ubi to fedora, where certain package names can differ slightly. 

When I try defining an arg in my image descriptor or in an override like so:

```
###### START module 'developer-base:17'

RUN dnf -install -y ${OPENSSL_PKG} ...

###### END module 'developer-base:17'

###### START image 'dev-tools/dev-workspace-nested-fedora:fedora39'

        ARG OPENSSL_PKG="compat-openssl11"

###### END image 'dev-tools/dev-workspace-nested-fedora:fedora39'
```

I'm sure there are good reasons for processing the image descriptor last, but it would be really great to have some sort of option to inject some sort of image level args that can be parsed by modules.

**Comment by rnc** [comment]
Fixed by #928
