### ISSUE TITLE
add authentication to artifacts

### ISSUE THREAD

**Issue by dortlii** [cekit/cekit#917]
**Describe the solution you'd like**
I'm missing the possibility to add authentication (like tokens, username/password) when using artifacts in cekit. The option to use URL artifacts is pretty nice, if the repository is accessable without any authentication.

This would be a nice addition:

```diff
   name: "jolokia"
   url: "https://github.com/rhuss/jolokia/releases/download/v1.3.6/jolokia-1.3.6-bin.tar.gz"
   # The md5 checksum of the artifact
   md5: "75e5b5ba0b804cd9def9f20a70af649f"
+ token: verysecure
```
or for older repos
```diff
   name: "jolokia"
   url: "https://github.com/rhuss/jolokia/releases/download/v1.3.6/jolokia-1.3.6-bin.tar.gz"
   # The md5 checksum of the artifact
   md5: "75e5b5ba0b804cd9def9f20a70af649f"
+ username: downloader
+ password: secureone
```

**Additional context**
Maybe I've missed the part in the documentation or an already open issue. Any help and suggestions are appreciated.

**Comment by rnc** [comment]
Thats an interesting idea and one we have not had a use-case for yet. I am not convinced though that storing passwords in the cekit descriptor yaml is a good way forward though. Currently the code for downloading the artifacts (eventually) routes to https://github.com/cekit/cekit/blob/develop/cekit/tools.py#L38 i.e. its using fairly standard libraries.

**Comment by dortlii** [comment]
True that, storing the passwords directly in the descriptor yaml wouldn't be good. I like the idea with the extension of the configuraiton file.

I'm using a GitLab pipline with buildah, so I could generate the config file with variables in the pipeline runtime. So no tokens or passwords need to be checked in.

**Comment by rnc** [comment]
@dortlii Thanks for the input/reply. I've had a brief play around with this and think we could make it work with something like
```
  -        res = urlopen(url, context=ctx)
  +        request = urllib.request.Request(url)
  +        if config.get("common", "url_authentication"):
  +            domains = dict([x.split("#") for x in config.get("common", "url_authentication").split(";")])
  +            for d, a in domains.items():
  +                if parsed_url.hostname == d:
  +                    b64auth = base64.b64encode(a.encode('latin-1')).decode()
  +                    request.add_header("Authorization", f"Basic {b64auth}")
  +                    break
  +
  +        res = urlopen(request, context=ctx)
```
I'll discuss this idea with the team when I return from holiday (and obviously it still needs docs/tests).

**Comment by dortlii** [comment]
is there already an approximate release date? I see that @goldmann 's review is pending on the PR and would be so happy to use the authentication feature in our image build process.

Thanks a lot for your work already!

**Comment by rnc** [comment]
@dortlii I'll do a release this week. Apologies for the delay.

**Comment by rnc** [comment]
Done : https://github.com/cekit/cekit/releases/tag/4.13.0

**Comment by dortlii** [comment]
Thanks a lot for your work @rnc !
