### ISSUE TITLE
Support for Docker build secrets

### ISSUE THREAD

**Issue by asingh3-atlassian** [cekit/cekit#924]
**Descrption**
For Docker builder in CEKit, there is no way to pass the build secrets to the Docker container. Is that something that can be added to the CEKit capabilities?
https://docs.docker.com/build/building/secrets/

**Additional context**
We are migrating from Ubuntu to Ubuntu (Pro) which requires us to mount a secret token to get access to the Pro repository. But, I didn't find a good way to run an underlying command like `docker build . --secret id=pro-attach-config,src=pro-attach-config.yaml`, using CEKit.
There are more details on how to use Ubuntu (Pro): https://documentation.ubuntu.com/oci-registries/en/latest/oci-how-to/enable-pro-services/

**Comment by rnc** [comment]
You're correct there is (currently) no way to pass arbitrary arguments through to the underlying builder (be that docker, podman or buildah). While `--build-arg` was added recently in #868 this doesn't help your use-case. I think it would be fairly straight-forward to add `--secret` although I do wonder if a more generic format might be better for longer term e.g. `--build-tool-flag=--secret=id=pro-attach-conf`

**Comment by rnc** [comment]
Is it just the arbitrary extra flags to docker you would require? (i.e. following the prior PR pattern in order to add extra flag capability) ? Would this be something you would be interested in contributing?

**Comment by rnc** [comment]
I've had a further look into this - while for podman and buildah this is relatively straight-forward, for docker its another question. Currently for docker we use the docker-py library to interface. This does **not** support secrets (See https://www.github.com/docker/docker-py/issues/2174 and https://www.github.com/docker/docker-py/issues/2230). Realted to this is #775
