### ISSUE TITLE
Support ``curl`` as alternative to downloading artifacts

### ISSUE THREAD

**Issue by rcernich** [cekit/cekit#96]
I'm not sure if this is something we should support, but a lot of Dockerfiles use curl to download artifacts from the web, so...as opposed to downloading the artifact before the build, have an option to use ``curl`` commands in the Dockerfile instead.

**Comment by dbecvarik** [comment]
Why not. I like that idea.

**Comment by goldmann** [comment]
Using `curl` can be done as part of module installation scripts. Rejecting as a general feature.
